### ISSUE TITLE
Funny alternative to JSS.

### ISSUE THREAD

**Issue by trusktr** [jsstyles/jss#110]
Just thought I'd link to this funny repo: https://github.com/The-Feminist-Software-Foundation/DICSS (look who forked it!). x}

**Comment by kof** [comment]
you mean the The-Feminist-Software-Foundation ?

**Comment by trusktr** [comment]
They forked DICSS. DICSS is similar to JSS (javascript-based styles with object literals, including the use of `&` for nesting).

**Comment by kof** [comment]
yeah, I saw it, though very limited minimalistic implementation  ....
