### ISSUE TITLE
[jss-cli] Valid JSON

### ISSUE THREAD

**Issue by afanasy** [jsstyles/jss#161]
Hi,

When converting css to jss, it adds semicolon `;` in the end of the file. This is fine for js, but it's invalid JSON. Would be nice either drop semicolon, or add an option to produce valid json.
Plus, prefixing with `module.exports =` is not needed for .json 

Спасибо за отличную библиотеку! :)

**Comment by kof** [comment]
Can you send me a PR?

**Comment by kof** [comment]
done and published

**Comment by afanasy** [comment]
:+1:
