### ISSUE TITLE
[all plugins] Link to here to file issues

### ISSUE THREAD

**Issue by isiahmeadows** [jsstyles/jss#171]
I noticed the issues were disabled on the plugin repos, but there isn't any readme directions pointing to file issues here [on](https://github.com/jsstyles/jss-px) [many](https://github.com/jsstyles/jss-vendor-prefixer) [of](https://github.com/jsstyles/jss-camel-case) [them](https://github.com/jsstyles/jss-extend). Could either issues be enabled on them or directions to file plugin issues here be added?

I'm not sure which one is best, but I did file [PRs](https://github.com/jsstyles/jss-nested/pull/9) [against](https://github.com/jsstyles/jss-extend/pull/3) [each](https://github.com/jsstyles/jss-vendor-prefixer/pull/7) [of](https://github.com/jsstyles/jss-camel-case/pull/4) [them](https://github.com/jsstyles/jss-px/pull/2).

**Comment by kof** [comment]
A link to the issues is fine. The plan is to use one central issues tracker from jss repository. If you Update the prs with a link to it, I can merge it.

**Comment by isiahmeadows** [comment]
@kof Good catch! (That was a mistake on my part...)

**Comment by isiahmeadows** [comment]
Done.

**Comment by kof** [comment]
all prs merged, thanks
