### ISSUE TITLE
[question] To create `new Jss()` or not to create `new Jss()`? That is the question.

### ISSUE THREAD

**Issue by trusktr** [jsstyles/jss#173]
I'm wondering if there's an advantage to creating new instances of `Jss` for each component in an app, or just using a single instance. For example, what I currently am doing is this:

```js
import jss from '/app/src/both/jss-configured'

let stylesheet = jss.createStyleSheet({
    motorDomSceneContainer: {
        position: 'absolute',
        overflow: 'hidden',
        width:    '100%',
        height:   '100%',

        '& .motor-dom-scene': {
            width:    '100%',
            height:   '100%',
        },
    },
}).attach()
```

where `/app/src/both/jss-configured` creates and configures a single `new Jss()` instance that is exported for all components to use.

Is there an advantage of one way over the other?

**Comment by kof** [comment]
You need to use different instances if you have conflicting setups in your components or app. If none of components needs different setup, use one global jss, which is created per default. If some components might need a different setup, use separate instance per app. If every component needs a different setup - use instance per component (will never be the case I hope.).

**Comment by trusktr** [comment]
Cool, thanks. Yeah, for now I'm just applying all plugins to a single instance, which might be overkill, but, I haven't really noticed a performance hit in practice.
