### ISSUE TITLE
Check for existence of class?

### ISSUE THREAD

**Issue by brandondurham** [jsstyles/jss#178]
I’m using the following to create a class and rule-set using the following code:

```javascript
// Create CSS class
const className = fontClassName(selectedFamily.label, selectedStyle.value);

const sheet = jss.createStyleSheet({ // eslint-disable-line no-unused-vars
	[`.${className}`]: {
		'font-family': `"${selectedStyle.label}"`,
		'font-weight': selectedStyle.weight,
		'font-style': selectedStyle.style
	}
}, {
	named: false
}).attach();
```

`fontClassName` is simply a utility function that creates a formatted string to use as a CSS className, like this: `.theFont__Font-Family--Font-Style`.

The class and StyleSheet are created on-the-fly based on a user’s selection in a toolbar. Once they make a selection I’d like to first check to see if the class already exists before creating a new one, but I’m not sure if JSS offers this functionality or how I would access it.

Suggestions?

**Comment by brandondurham** [comment]
There should be a name for that condition where you spend an hour on something, can’t find the answer, ask for help in a forum, then immediately figure it out.

Checked your API docs and found the answer (I think).

Now creating an empty stylesheet when the component mounts:

```javascript
let styleSheet;
componentDidMount() {
	styleSheet = jss.createStyleSheet({}, {
		named: false
	}).attach();
}
```
… then checking for a rule before adding a new one:
```javascript

// Create CSS class
const className = fontClassName(selectedFamily.label, selectedStyle.value);

// Add the CSS rule-set if it doesn’t already exist
if (!styleSheet.getRule(`.${className}`)) {
	styleSheet.addRule(`.${className}`, {
		'font-family': `"${selectedStyle.label}"`,
		'font-weight': selectedStyle.weight,
		'font-style': selectedStyle.style
	});
}
```
This the right way to go?

**Comment by kof** [comment]
yes, getRule is what you wanted.
