### ISSUE TITLE
[experiment] JSS language

### ISSUE THREAD

**Issue by kof** [jsstyles/jss#182]
The idea is to allow:
- property names to be any chars, including spaces and dashes without the need to write quotes around them
- all CSS primitives like 'left', 'calc' , '10px' etc. written without quotes inside of objects

The output after conversion will be a valid javascript, where all CSS tokens are quoted.

This will make writing css in javascript much nicer.

When this converter is done - JSS becomes a language on top of javascript and css.

Example
```
const font = {
  font-size: 12px,
  line-height: 1
}

export default {
  button: {
    extend: font,
    border: none,
    transition: background 0.3s color 0.3s font-size 0.3s,
    &:before: {
      content: 'icon'
    }
  },
  redButton: {
    extend: 'button',
    background-color: red,
    &:hover: {
      border: 1px solid blue
    }
  },
  @media (min-width: 1024px): {
    button: {
      font-size: 16
    }
  }
}
```

**Comment by watilde** [comment]
If this feature will generate JavaScript code as an intermediate representation, I think there are two way to write a property which need to use dash like the following codes. Could I ask you which one do you expect?
```diff
'&:before': {
--  content: '"icon"'
++  content: "icon"
}
```
or
```diff
'&:before': {
--  content: '"icon"'
++  content: \"icon\"
}
```

**Comment by kof** [comment]
The output would be exactly what it is right now without precompile step, I think.

**Comment by kof** [comment]
Modified description.

**Comment by trusktr** [comment]
It's like JSX for CSS. CSX? I really like the idea!

**Comment by kof** [comment]
After some consideration, I don't really like the idea any more. This will bring lots of ambiguity and a compilation step to JSS. Right now it is pure, this is worth a lot.
