### ISSUE TITLE
Configurable class name pattern

### ISSUE THREAD

**Issue by artin-phares** [jsstyles/jss#190]
With CSS Modules and webpack I can configure pattern of generated CSS class names like this:
`localIdentName=[name]__[local]___[hash:base64:5]`

Can I do that with JSS?..

**Comment by kof** [comment]
Not yet, tell me why you want to be able to do that, then we can think about a solution.

**Comment by artin-phares** [comment]
@kof, sure.
I'm investigating into direction of using both CSS Modules and JSS on the project.
Like this:
- CSS Modules allows me to write css **outside** of my components
- JSS allows me to have css **inside** my components (e.g. for small component I do not want to create separate .css file)

At this point everything is ok.
(btw, i'm using webpack, react, react-jss)

What I need here is **consistent** css class names for both approaches.

So with CSS Modules I can specify pattern like `{ComponentName}_{LocalCssClassName}`
With JSS I have `ComponentName_LocalCssClassName--jss-0-27`
I do not need that `--jss-x-x` postfix...

**Comment by kof** [comment]
I don't quite understand how are you going to use those "consistent" class names. They are generated and are not ment to be used directly.

**Comment by artin-phares** [comment]
Yes, usually we do not care about generated class names.
But I need to allow users ability to customize UI through rewriting css rules through their custom css files.
So I cannot have random hash part in class names.

**Comment by kof** [comment]
Thats why there is a generated hash on a class name. Its a security against somebody using this selector to overwrite styles from the outside.

What you are going to do is bad. Rethink your design.

**Comment by artin-phares** [comment]
Yep, rewriting styles is bad.
Sometimes we have old projects and compatibility issues.

**Comment by kof** [comment]
For this case you way want to add additional class names to elements.

**Comment by kof** [comment]
Also I don't have enough insides to your project, maybe there is a better approach, how to solve that.

**Comment by kof** [comment]
also as a hack, you can overwrite the function responsible for class generation in jss and use whatever pattern you want. Your use case just doesn't justify a public api change.

**Comment by artin-phares** [comment]
@kof, sure. Additional class names will result in too many classes on each element.
And I'm sure, some of users will add rewrite on some random class like 'component-jss-45-168'. And that binding will break on next update...

Honestly, I do not see any good approach to allow users to customize styles of your app, consider this app as template app, which is usually customized to needs of concrete customer.

On one hand I need styles isolation for my components to make sure I have no collision with other components. On the other hand, I have to provide customization of those styles to customers...

Odd, and not the case web developers usually have.

Thanks anyway!

**Comment by kof** [comment]
Thats your task as an engineer to find a proper solution for you project, in general there are approaches for theaming. It has nothing to do with jss itself.

For e.g. take a look at 

https://github.com/markdalgleish/react-themeable

And this discussion:

https://github.com/nikgraf/future-react-ui/issues/1

**Comment by artin-phares** [comment]
Looks promising. Will go deep into that later. Thanks.

**Comment by artin-phares** [comment]
Just a quick question. Does this approach allows me to dynamically change custom themes? Like, put one styles definition, reload page, put another one... without rebuilding?..

**Comment by kof** [comment]
sure.

**Comment by artin-phares** [comment]
nice

**Comment by HenriBeck** [comment]
@Korayem see: http://cssinjs.org/js-api?v=v9.8.7#generate-your-own-class-names

**Comment by Ninjef** [comment]
I keep seeing this link (http://cssinjs.org/js-api?v=v9.8.7#generate-your-own-class-names) wherever I search for an answer to creating custom class names using JSS, but that link is 404ing. Can the solution be found somewhere else?

**Comment by HenriBeck** [comment]
Yes: this is now located here: https://cssinjs.org/jss-api?v=v10.0.0-alpha.9#generate-your-class-names

**Comment by kof** [comment]
Yeah we broke URLs with v10 of the lib and new site structure. We should do it better in the future ... not sure how though.

**Comment by airtonix** [comment]
@Korayem like this: 

```

import React from 'react';
import classnames from 'classnames';


function Foo ({
  classes = {},
  className,
  isBar,
  name,
  value,
  ...props
}) {
  return (
    <div className={classnames(
        'static-foo-classname',
        isBar && 'static-foo-classname--is-bar',
        className,
        classes.container,
        isBar && classes.containerIsBar
    )}>
        <div className={classnames(
            'static-foo-classname__name',
            className,
            classes.name
        )}>
        {title}
        </div>
        <div className={classnames(
            'static-foo-classname__value',
            className,
            classes.value
        )}>
            {value}
        </div>
    </div>
  )
}
```
