### ISSUE TITLE
v3.4.0 breaks v3.3.0 compatibility

### ISSUE THREAD

**Issue by jeffora** [jsstyles/jss#194]
3.4.0 has introduced breaking changes to some users of 3.3.0, potentially because of the move to Babel 6. With this commit (https://github.com/jsstyles/jss/commit/67484c9e023a7f6f0d5be86cdd02b6ca828d38f0), named exports were added in addition to a default export. Babel 5 allowed a property of the default export to be imported as such: `import {create} from 'jss'` (e.g: https://github.com/qimingweng/react-modal-dialog/blob/master/src/useSheet.js#L1), and this would bind `create` to `(new Jss()).create`. However, Babel 6 is a little stricter on these semantics. Additionally, the addition of explicit named exports might have complicated things. @loganfsmyth has kindly offered to add more details if needed.

At any rate, in 3.3.0 `import {create} from 'jss'` was valid, functional syntax, and in 3.4.0 it breaks with `create is not a function`.

**Comment by kof** [comment]
Yeah, I realized that just recently, not sure what to do now. What is your setup? For me as for babel user, that change didn't break anything.

**Comment by kof** [comment]
Also all the plugins has been updated to babel 6 without to increment the major version.

**Comment by loganfsmyth** [comment]
Either the Babel 6 upgrade, or the addition of the new named exports would have triggered this. In Babel 5, if you have _only_ a default export, it behaves exactly like `module.exports = new Jss();`, but if you have a default and named exports, you're doing `exports.default = new Jss()`. Babel 6 made this behavior consistent by _always_ doing `exports.default = new Jss()` even in the case where there is only a default.

You'll want to change your exports to recreate the "named" export behavior you were getting from Babel 5. I'd probably do this.
```
const jss = new Jss();

export default jss;
export function create(...args){
    return jss.create(...args);
}
export function createStyleSheet(...args){
    return jss.createStyleSheet(...args);
}
export function createRule(...args){
    return jss.createRule(...args);
}
export function use(...args){
    return jss.use(...args);
}
```

Note this means `module.exports` won't be an instance of `Jss` anymore, but hopefully that's an acceptable change?

**Comment by jeffora** [comment]
My setup: we have a dependency on `react-modal-dialog@2.0.0` which has a semver range dependency on `jss`. It uses the above `import {create} from 'jss'` syntax which breaks on 3.4 but worked on 3.3, so our build server got the latest jss and our app broke on runtime. I've opened a PR to `react-modal-dialog` but it doesn't seem very actively maintained.

**Comment by kof** [comment]
module.exports not being Jss instance might be also a breaking change for someone else ...

**Comment by loganfsmyth** [comment]
@kof That one's a harder call. If that's a concern, my recommendation would be to use ES6 imports and CommonJS exports in your `index.js`

**Comment by loganfsmyth** [comment]
Keep in mind, that means your new testing exports are just going to be properties tacked onto the `Jss` instance then.

**Comment by kof** [comment]
yeah, I could just provide a hotfix in the version 3.5.0 for the breaking change and then remove it in the version 4.0.0

**Comment by jeffora** [comment]
> module.exports not being Jss instance might be also a breaking change for someone else ...

Isn't that already the case? Doesn't the addition of the named exports mean that the jss instance is already on `module.exports.default`?

**Comment by loganfsmyth** [comment]
@jeffora Yes, but that's potentially an unexpected change from the Babel 5 upgrade.

**Comment by kof** [comment]
yep, its multiple breaking changes
1. module.exports is not Jss instance any more
2. import {create} 'jss' doesn't work, because of the 1. point.

**Comment by kof** [comment]
will have something in a bit, stay tuned

**Comment by kof** [comment]
3.5.0 would be this:

```
import Jss from './Jss'
import StyleSheet from './StyleSheet'
import Rule from './rules/Rule'

const jss = new Jss()

module.exports = exports = jss

/**
 * Creates a new instance of Jss.
 *
 * @see Jss
 * @api public
 */
function create() {
  return new Jss()
}

export {
  create,
  // For testing only.
  Jss,
  StyleSheet,
  Rule
}

export default jss
```

4.0.0 would be removal of `module.exports = exports = jss`

**Comment by kof** [comment]
Note: I moved create function from Jss class to the index, in never fit well there anyways.

**Comment by kof** [comment]
@jeffora @loganfsmyth would this work for everybody?

**Comment by loganfsmyth** [comment]
I agree that'll work. The main downside I see:
1. You're now moving the `create` function from the object prototype to an object property, which may be fine, but is a difference.
2. You're putting the `Jss`, `StyleSheet`, and `Rule` constructors into the Jss instance until 4.x, which may be fine.

I don't know this codebase super welll. Those don't seem like deal-breakers though, as long as the `Jss` instance doesn't mind having some of its properties overridden.

**Comment by jeffora** [comment]
Removing the create function from the class is a breaking change as well though? That would require a major version bump.

**Comment by kof** [comment]
@loganfsmyth Jss doesn't mind, its very small ....
@jeffora how is moving create function a breaking change?

**Comment by loganfsmyth** [comment]
@kof Are you moving it, or just duplicating it into `index.js`? I assume the concern is `import jss from 'jss'; jss.create()`

**Comment by jeffora** [comment]
Right - `create` is currently part of the prototype, meaning any instance of Jss has it as a method, so if you remove it from the prototype it's a breaking change. This is currently possible: `(new Jss()).create().create().create()......` - if that becomes not possible (regardless of whether it's a good idea), it's a breaking change.

**Comment by kof** [comment]
true, I will postpone moving create function to the major version

**Comment by kof** [comment]
please check out, I also added some tests for the exports

**Comment by kof** [comment]
let me know guys if it works for you, I am waiting for your feedback before publishing.

**Comment by loganfsmyth** [comment]
That seems reasonable to me, I've never used this module though so I'll leave it to @jeffora. I was just chiming in as a source of Babel knowledge :)

**Comment by jeffora** [comment]
The update looks reasonable to me. I also don't use this directly, but rather as a dependency of a dependency. This should fix that use-case though. :+1:

**Comment by kof** [comment]
ok released

**Comment by jeffora** [comment]
Thanks for getting on this quickly!
