### ISSUE TITLE
requestAnimationFrame for attaching/detaching?

### ISSUE THREAD

**Issue by trusktr** [jsstyles/jss#196]
I wonder if requesting an animation frame when detaching or attaching a stylesheet would be beneficial for performance?

This is more of a note in order to eventually find out, and possibly improve on the experiments I was doing in https://github.com/jsstyles/jss/issues/34.

**Comment by kof** [comment]
yes, this is the task of rendering engine. If we request animation frames in jss, they will be not in sync with the rendering of a component:
so ideally, the function that renders the component, also triggers attaching.

**Comment by kof** [comment]
also user might choose to attach everything at the beginning and never detach ...
