### ISSUE TITLE
Usage example in README

### ISSUE THREAD

**Issue by trusktr** [jsstyles/jss#197]
I think it's  good idea to show a basic usage example in the README. That's one of the main things people look for immediately in a README I think (easier than having to figure out which links to follow). My theory is that that will also lead to more stars and adoption.

Show a simple React component using JSS perhaps, to show how JSS would let one write encapsulated component-based styles.

Just 2 cents. :]

**Comment by kof** [comment]
Don't know what you mean, there is an example, any suggestions how to make it more common?

**Comment by kof** [comment]
I assume you didn't see the example because you didn't scroll far enough, I changed the structure to fix this.

**Comment by trusktr** [comment]
@kof Oh, I see the example you have there, but it doesn't show the API usage. For example,

```js
let stylesheet = jss.createStyleSheet(...)
stylesheet.attach()
stylesheet.detach()
// apply rule to element, etc.
```

Showing this applied to a small HTML (possibly React) component would paint the picture a lot better.

**Comment by kof** [comment]
better?

**Comment by trusktr** [comment]
Better!
