### ISSUE TITLE
[react-jss] Plugins don't work when using jss.create()

### ISSUE THREAD

**Issue by mindjuice** [jsstyles/jss#198]
I followed the example in "Create an own instance of JSS" [here](https://github.com/jsstyles/jss/blob/master/docs/js-api.md#create-an-own-instance-of-jss), but none of the plugins work in that configuration.  For example, I had the `jss-camel-case` plugin installed and configured with `jss.use(camelCase())`, but the browser still showed the camel case version of `fontFamily` instead of `font-family`.  JSS itself was otherwise working fine (meaning stylesheets were being attached properly).

I changed the code to use `import jss from 'jss'` instead, and then the plugins worked as expected.

I'm also using JSS through `jss-react`.

This version of my file `/utils/jss.js` (my wrapper for JSS) doesn't work:

    import { create } from 'jss';
    import camelCase from 'jss-camel-case';
    import reactJss from 'react-jss';

    export const jss = create();
    export const useSheet = reactJss(jss);
    jss.use(camelCase());

This version does work, but then doesn't have the benefit of being a separate instance:

    import jss from 'jss';
    import camelCase from 'jss-camel-case';
    import reactJss from 'react-jss';

    export const useSheet = reactJss(jss);
    export jss from 'jss';

    jss.use(camelCase());

**Comment by kof** [comment]
are you using latest versions? Is it possible that you use multiple jss versions in your build?

**Comment by mindjuice** [comment]
I'm on the following versions, which I believe are all the latest:

    $ npm list | grep jss
    ├── jss@3.6.0
    ├── jss-camel-case@1.0.2
    ├── jss-default-unit@2.1.1
    ├── jss-extend@1.2.1
    ├── jss-nested@1.0.3
    ├── jss-props-sort@1.0.1
    ├─┬ jss-vendor-prefixer@1.0.1
    ├── react-jss@2.0.5

I don't see any duplicates in the npm list above either.

**Comment by kof** [comment]
Ok now I need something reproducible, can you give me a full working example?

**Comment by kof** [comment]
I think I have got that issue myself, hold on. Something was broken in the recent releases.

**Comment by kof** [comment]
How do you apply useSheet to your components?

**Comment by kof** [comment]
If you were doing useSheet(Component, styles) I found the bug in react-jss and just released a 2.0.6 version which fixes the problem.

**Comment by mindjuice** [comment]
Yes, that's what I was using.  I'll try the fix in a couple of hours.

Thanks.

**Comment by mindjuice** [comment]
Forgot to reply to this the other day.  It's working for me with your change.

Thanks. :+1:
