### ISSUE TITLE
[jss] Can't have multiple @font-face entries in a stylesheet

### ISSUE THREAD

**Issue by mindjuice** [jsstyles/jss#199]
You can have a stylesheet with a single `@font-face` entry in it, and it works fine, however, I have multiple fonts I want to include on a stylesheet.  From the code, this seems not possible today (let me know if I missed something).

If the style behind the `@font-face` object key were optionally an array instead of an object, then you could have multiple fonts.

    '@font-face': [
      {
        fontFamily: 'Lato-Regular',
        src: 'url("/fonts/Lato-Regular.ttf") format("truetype")',
      },
      {
        fontFamily: 'Lato-Bold',
        src: 'url("/fonts/Lato-Bold.ttf") format("truetype")',
      },
    ],

  The `toString()` function in `FontFaceRule.js` could be modified something like this:

    toString(options) {
      let str = ''
      if (Array.isArray(this.style)) {
        for (let index = 0; index < this.style.length; index++) {
          str += toCSS({...this, style: this.style[index]}, options)
        }
        console.log('@font-face CSS =  ' + str)
        return str
      }
    
      return toCSS(this, options)
    }

Thoughts?  If this sounds good, I can submit a PR.

**Comment by kof** [comment]
Yes, sounds good, will accept a PR

**Comment by mindjuice** [comment]
FYI, I got this working tonight, but don't have time to polish it up and write unit tests until tomorrow.

I had to add a bit of code to `run()` in  `PluginsRegsitry.js' to iterate over `rule.style` if it's an array.

**Comment by kof** [comment]
PluginsRegistry shouldn't be needed for this task, but let me see what you did.

**Comment by mindjuice** [comment]
Might be able to do it another way, but running the plugins on an array of styles as shown in my original message above ended up returning an object of styles with numbers as the keys, and then in `FontFaceRule.toCSS()`, I couldn't tell the difference between a normal style object and an array.

I'll send a PR in the morning, but here are the two changes:

PluginsRegistry.js

    run(rule) {
      const runPlugins = (rule2) => {
        for (let index = 0; index < this.registry.length; index++) {
          this.registry[index](rule2)
        }
      }

      if (Array.isArray(rule.style)) {
        for (let index = 0; index < rule.style.length; index++) {
          const style = rule.style[index]
          const copyOfRule = {...rule, style}
          runPlugins(copyOfRule)
          rule.style[index] = copyOfRule.style
        }
      }
      else {
        runPlugins(rule)
      }
    }

FontFaceRule.js

    /**
     * Generates a CSS string.
     *
     * @see toCSS
     * @api public
     */
    toString(options) {
      let str = ''
      if (Array.isArray(this.style)) {
        for (let index = 0; index < this.style.length; index++) {
          str += toCSS({...this, style: this.style[index]}, options)
          str += '\n'
        }
        return str
      }

      return toCSS(this, options)
    }

**Comment by kof** [comment]
We def. need to get rid of that part in plugins registry. Because the code you wrote broke the knowledge encapsulation of plugins registry. All it needs to know is there are plugins and rules. In your case it knows that a rule can have style array etc. This is an internal knowledge of the rule.

Also `toCSS({...this, style:` is not good, we should not need to copy an instance just to set style as an obejct. Most probably we need to modify the toCSS function.

**Comment by mindjuice** [comment]
Yeah, I didn't intend that this would be the final code.  Was just experimenting to learn the code base a bit and see if I could make it work.  It's definitely janky ATM.

I originally had that `PluginsRegistry.js` change in `Stylesheets.js`, but then realized that`Jss.js` would need to do the same thing, so I moved it.  The only reason I tried doing any of that though is that `plugins.run()` changes the style it's given from an array of objects to an object of objects, and also doesn't run plugins on the entries of the array.

For example, given the following `style` array: 

    [
      {
        fontFamily: Lato-Regular;
        src: url("/fonts/Lato-Regular.ttf") format("truetype");
      },
      {
        fontFamily: Lato-Bold;
        src: url("/fonts/Lato-Bold.ttf") format("truetype");
      }
    ]

it gets converted to the following after `plugins.run(rule)` (notice that no camelCase plugin conversion occurred):

    {
      0: {
        fontFamily: Lato-Regular;
        src: url("/fonts/Lato-Regular.ttf") format("truetype");
      },
      1: {
        fontFamily: Lato-Bold;
        src: url("/fonts/Lato-Bold.ttf") format("truetype");
      }
    }

Then the `toString()` method generates the following, but since the plugin didn't run, the rules are wrong:

    @font-face {
      fontFamily: Lato-Regular;
      src: url("/fonts/Lato-Regular.ttf") format("truetype");
    }
    @font-face {
      fontFamily: Lato-Bold;
      src: url("/fonts/Lato-Bold.ttf") format("truetype");
    }

I thought about putting code in `createRule()` to handle the array case and generate multiple rules, but all code expects `createRule()` to return a single rule.

Right now the only thing preventing it from working is that `plugins.run(rule)` doesn't work when `rule.style` is an array.  I can wrap the two calls to `plugins.run(rule)` (in `Jss.js` and `Stylesheets.js`) with code that checks for `rule.style` being an array, but since `plugins.run(rule)` expects a `rule`, I need to make a temporary object that has the same rule fields, but has `style` set to `style[index]`.

Obviously I'm not as familiar with the code yet as you, so please let me know if you see a better way.

Where is the best place for the code to know about styles being arrays?

**Comment by kof** [comment]
Wait, which plugins are you talking about, non of them should touch this rule, if they do, its a bug.

**Comment by mindjuice** [comment]
I'm running a bunch of them, but I just tried using only `jss-camel-case` and it converts it.

If I remove the `jss.use(camelCase())`, then the style is still an object.

**Comment by mindjuice** [comment]
https://github.com/jsstyles/jss-camel-case/blob/master/src/index.js#L13

**Comment by kof** [comment]
yep, its a bug, font-face rule has been introduce recently as a separate abstraction, before that it was rendered by Rule.

I need to update plugins.

**Comment by kof** [comment]
so camelCase plugin needs to know this about the font-face rule and handle it properly.

**Comment by kof** [comment]
jss-default-unit, jss-props-sort need to ignore any rules other than 'regular'.

**Comment by mindjuice** [comment]
If you haven't started these changes yet, I should have some time tomorrow afternoon to work on them all.

**Comment by kof** [comment]
waiting for your pr

**Comment by mindjuice** [comment]
I submitted PRs for `jss` and `jss-camel-case` today.  I'll try to update `jss-default-unit` and `jss-props-sort` tomorrow.

**Comment by mindjuice** [comment]
Sorry, I forgot about your comment on the copy via the spread in `FontFaceRule.js` `toString()` function.

I can refactor the `toCSS()` function to take `selector` and `style` instead of `rule` tomorrow to avoid that copy.

**Comment by mindjuice** [comment]
Just updated the PR for this to change `toCSS()` to work as I mentioned in my last post.

**Comment by kof** [comment]
So we need also to update the other  2 plugins to ensure they don't break, then we can release all together.

**Comment by mindjuice** [comment]
Working on them now.

**Comment by kof** [comment]
ok published all plugins and published new jss version. @mindjuice please check everything if I didn't miss something.
