### ISSUE TITLE
Support for styling tags like html, body, button, etc.

### ISSUE THREAD

**Issue by mindjuice** [jsstyles/jss#202]
It seems it's not possible to style tag types like `html`, `body`, `a`, etc.  It ends up generating class styles for them instead.

Is this on purpose?

Should I just continue using normal .css or .less for those global tag definitions?

It seeems like an easy thing to support if we have some syntax to differentiate class names from tag names.

Maybe `'<html>': { boxSizing: 'border-box' }`?  This lets us keep the nice current syntax for classes at the expense of a non-standard syntax for tag types.

Alternatively, if that syntax is too unwieldy, we could just assume that if you use an HTML tag name as the style name, like `button: { }`, that you want the tag `button`, not a class `.button`.  Then you could disambiguate with something like `'.button': { }` if you actually wanted a class-based style.

**Comment by kof** [comment]
added documentation to json-api 

https://github.com/jsstyles/jss/blob/master/docs/json-api.md#writing-global-selectors

Before that there has been already documentation in js-api:

https://github.com/jsstyles/jss/blob/master/docs/js-api.md#create-regular-style-sheet-with-global-selectors

**Comment by mindjuice** [comment]
I think the documentation for this wasn't clear to me.  I didn't know what was meant by "global" at the time I skimmed over it, and also, the example doesn't include a tag type like `div` or `span`.

I'm going to spent some time soon going over the documentation to try improve things now that I understand JSS better.

**Comment by kof** [comment]
great!

**Comment by gbersac** [comment]
Those documentation link are outdated @kof 

But the solution is to use `@global`:

```javascript
const useStyles = createUseStyles({
    "@global": {
        body: {
            backgroundColor: theme.backgroundGrey,
            fontFamily: "sans-serif",
        },
    },
})
```
