### ISSUE TITLE
Automation testing by CI

### ISSUE THREAD

**Issue by watilde** [jsstyles/jss#213]
Do you have a plan to add `.travis.yml` into this project? It would be helpful for contributors.
+ https://travis-ci.org/

**Comment by kof** [comment]
it is already automated, currently using codeship and browserstack

**Comment by kof** [comment]
Need to make pull requests run the tests too.

**Comment by kof** [comment]
Probably I need to move awai from codeship because it doesn't seem to allow to trigger builds for non-team members at codeship

**Comment by kof** [comment]
can you try to send a new pr? I did something in codeship config, maybe it will display it now.

**Comment by watilde** [comment]
Sure thing!

**Comment by kof** [comment]
Just got an answer from codeship support, they are "working" on adding public builds. It is not supported currently. We need to move to something else, most probably travis.

**Comment by kof** [comment]
done
