### ISSUE TITLE
hover did not get compile correctly

### ISSUE THREAD

**Issue by LeoAJ** [jsstyles/jss#217]
This is the `css` I got when I use `hover`...

<img width="256" alt="screen shot 2016-04-20 at 4 26 18 pm" src="https://cloud.githubusercontent.com/assets/492921/14693556/ced1508e-0714-11e6-8ddc-e2afbe035a61.png">

Am I missing something??

Attach my component code;

```js
import React, { PropTypes } from 'react';
import useSheet from '../useSheet';

const style = {
  button: {
    fontSize: 12,
    '&:hover': {
      background: 'blue'
    }
  },
  img: {
    maxWidth: '360px',
    maxHeight: '360px',
    borderRadius: '3px',
    '&:hover': {
      cursor: 'zoom-in'
    }
  }
};


const Image = () => (
  <div></div>
);

export default useSheet(Image, style);

```

This is `useSheet.js`,

```js
// jss
import { create } from 'jss';
import reactJss from 'react-jss';
import camelCase from 'jss-camel-case';
import vendorPrefixer from 'jss-vendor-prefixer';

const jss = create();
jss.use(camelCase());
jss.use(vendorPrefixer());

export default reactJss(jss);

```

Thanks!

**Comment by kof** [comment]
yep, you didn't add jss-nested plugin which is responsible for & parsing. Please point me to the place where you missed it in documentation so that I can fix the docs.

**Comment by kof** [comment]
Or of course you could send me a PR for documentation.

**Comment by LeoAJ** [comment]
Hi @kof Thanks, it works now.

In `jss` doc you had `hover` as an example there so I thought it will just work not required other plugin for that. That is where I started and maybe that is why I got confused.

Thanks anyway, you are welcome to close this issue if you want, appreciated the help!
