### ISSUE TITLE
[jss-default-unit] feature: use `is-number` to be able to accept strings

### ISSUE THREAD

**Issue by tunnckoCore** [jsstyles/jss#224]
you can use http://npm.im/is-number ;] But be aware of that it have bug currently (https://github.com/jonschlinkert/is-number/issues/3) and returns `true` for `' '`.

**Comment by kof** [comment]
It wasn't necessary so far. Currently if you want to get a default unit, use numbers. Let's see if cssx will get the fix soon https://github.com/krasimir/cssx/issues/6

**Comment by kof** [comment]
I think we should auto add units to numeric values. Not touching a string gives us a way to avoid auto unit plugin. Closing it for now until this becomes a problem.
