### ISSUE TITLE
[jss-nested] generate JSS classNames from nested rules

### ISSUE THREAD

**Issue by yogiben** [jsstyles/jss#232]
```js
.message {
  .unread: {
    ...
  }
}
```

should be able to be used like

```js
<div classNames={classNames({[classes.message], [classes.message.unread]}) />
```

Does another solution exist?

**Comment by kof** [comment]
Don't even know how you came to this syntax and don't understand the problem you are trying to solve.

**Comment by yogiben** [comment]
In CSS it would be this
```css
.message {
   ...
}
.message.unread {
  ....
}
```

In nested jss it would be
```js
message: {
    ...
   '&.unread': {
     ...
  }
}
```

The problem is that, while I can use the className generated by jss for the `.message` class, I cannot use it for the nested `.unread` class.

This forces me to use a global `unread` class.

**Comment by kof** [comment]
Selector after & is global, I recommend not to use global classes at all.  Currently it is not possible to nest rules and make them non-global at the same time, see #214, most of the time you don't need it  anyways.

You can create separate rules for  message and for unread message and swap classes out.

```javascript
{
  message: {...}
  unreadMessage: {
    extend: 'message',
    color: 'red'
  }
}
```
