### ISSUE TITLE
Better JSS logo

### ISSUE THREAD

**Issue by okonet** [jsstyles/jss#236]
The current logo is nice, but in my opinion it doesn't reflect all sides of JS and CSS, that JSS is representing.

This is my proposal of the JSS logo:

![explanation](https://cloud.githubusercontent.com/assets/11071/15710803/db3c149a-280b-11e6-8538-130acea08a78.png)

![jss logo](https://cloud.githubusercontent.com/assets/11071/15710806/de8ea8ce-280b-11e6-88fb-c30719c5d0a5.png)

**Comment by kof** [comment]
Done! Added you to the organization for this contribution)
