### ISSUE TITLE
Observations and Differences

### ISSUE THREAD

**Issue by zoomclub** [jsstyles/jss#24]
First off, thanks for jss. I was just looking at react-styles and concerned that the style values were hardwired into the component (and to add a function to fetch the value based on the key would just trip up webpack). What I seek is a softwired approach where the style key-values are still optionally defined outside the component. This exact approach is what looks to be possible with jss, where sharing values and direct injection make this doable.

For me defining values in a separate "vars.js" file outside the components that use them is still the best. That way alternate vars.js files can be activated and multiple styles can be changed at once. The word I coined for what you called vars.js is decor files. I was defining them in pure json but I'll live with the js :)

Get this into react.js as soon as possible, your onto a good thing here. Its been a evolution from absurd.js to react-styles to jss, great progress!

**Comment by kof** [comment]
already using it with react https://github.com/jsstyles/react-jss
