### ISSUE TITLE
[jss-nested] thoughts regarding the placement of the & character

### ISSUE THREAD

**Issue by fgnass** [jsstyles/jss#240]
Since jss-nested currently requires the selectors to start with `&` it could in theory be made optional. The fact that a property value is an object could be enough to infer that it is a nested selector:

```js
{
  foo: {
    ":hover": { ... }
  }
}
```

Alternatively (?) it might be a good idea to allow the `&` to occur also at arbitrary locations, for example `'*:hover > &'`.

I'd love to hear your thoughts.

**Comment by fgnass** [comment]
Okay, the first would conflict with #225 which would also be nice to have :)

**Comment by kof** [comment]
There are 2 use cases where value can be an object and not a nested rule:

1. Media rules and co.
2. #225
