### ISSUE TITLE
[jss-theme] Plugin 

### ISSUE THREAD

**Issue by umidbekkarimov** [jsstyles/jss#243]
Plugin that allows to define basic theme settings.

Use example: 

```javascript
import jss from 'jss';
import {
    createTheme
} from 'jss-theme';

jss.use(createTheme({
    palette: {
        danger: 'red',
        success: 'green'
    }
}));

jss.createStyleSheet({
    btn: {
        backgroundColor: 'white'
    },

    btnDanger: {
        backgroundColor: '${palette.danger}'
    },

    btnSuccess: {
        backgroundColor: '${palette.success}'
    }
});
```

Basically it's just plain object storage, but *theoretically* we can use it to validate props and values as soon as theme object pattern will be defined

**Comment by kof** [comment]
It doesn't need to be a plugin, you can define it outside of jss and use real template strings instead.

**Comment by kof** [comment]
```javascript
import jss from 'jss';
import {
    palette
} from 'jss-theme';

jss.createStyleSheet({
    btn: {
        backgroundColor: 'white'
    },

    btnDanger: {
        backgroundColor: `${palette.danger}`
    },

    btnSuccess: {
        backgroundColor: `${palette.success}`
    }
});
```

**Comment by typical000** [comment]
Personally, I think that plugin for theming isn't needed. In my project:
**Main JSS sheet**:
```javascript
import vars from './Vars'
export default {
  logo: {
    color: vars.themeColor
  }
}
```
**And vars.js**
```javascript
const base = {
  bg: '#212121',
  color: '#878787',
  themeColor: '#ff5959',
  themeColorSecondary: '#05cf77',
}

export default {
  bodyBg: base.bg,
  bodyColor: base.color,

  themeFont: '"Open Sans", arial, serif',
  themeColor: base.themeColor,
  themeColorSub: base.themeColorSecondary,
  themeRadius: '4px',
  // And more variables...
}
```

**Comment by umidbekkarimov** [comment]
@kof @typical000 

I already using like that and I wanted to get rid of `singleton` file with settings and pass values from outside of component, may be there are better approach, I just got and idea and wanted to share it.

**Comment by kof** [comment]
@umidbekkarimov why do you want to get rid of that singleton? Also it doesn't need to be singleton, it can by anything you want. So why would you want to get rid of module system for getting the theme?

**Comment by umidbekkarimov** [comment]
@kof I have like 4 similar projects that share same components, and want to add add these components as separate npm package, but before this I need to figure out how to pass theme settings to these components.

**Comment by kof** [comment]
I don't see a problem, put your theme in a separate package and use it everywhere.

**Comment by umidbekkarimov** [comment]
@kof so I should use third party lib as theme provider

**Comment by kof** [comment]
Not sure what you mean by third party, your theme is just a number of constants, you can put it in a separate package, import it in all projects and use. Maybe I see the problem if you show some code.

**Comment by umidbekkarimov** [comment]
>  you can put it in a separate package, import it in all projects and use.

I meant that,

> Maybe I see the problem if you show some code.

Lets say I have component `Button`,
And it should accept `color` and `backgroundColor` values from theme.
Also I have 4 projects with different colour palletes
Now I have to pass these colours to the component.

```javascript
// somewhere in entry point
import {themeProvider} from 'some-theme-provider-lib';

const theme = {};

themeProvider.set(theme);

/// somewhere in component
import {themeProvider} from 'some-theme-provider-lib';
const theme = themeProvider.get();

@useSheet({
    root: {
        color: theme.pallete.color1,
        backgroundColor: theme.pallete.color2
    }
})

```

**Comment by kof** [comment]
oh I see the problem, you want to pass the colors dynamically, for this we have functions:

```javascript
export function getStyles(theme) {
   ...
}

@useSheet(getStyles(theme))

```

**Comment by kof** [comment]
What should I do with this issue, did we come to a consensus?

**Comment by umidbekkarimov** [comment]
> What should I do with this issue, did we come to a consensus?

Yep, you can close it
