### ISSUE TITLE
Node.js 6 Warning

### ISSUE THREAD

**Issue by jacksonrayhamilton** [jsstyles/jss#248]
When installing on Node.js 6, I get the following warning:

```
error: npm WARN engine jss@4.0.0: wanted: {"node":">=4.0.0 <6.0.0"} (current: {"node":"6.2.1","npm":"2.15.7"})
```

Is this package not supported on Node.js 6, or should the "engines" field be updated?

**Comment by kof** [comment]
if you tried node 6 and it works fine, then yes.

**Comment by kof** [comment]
also don't forget to run linter and tests

**Comment by jacksonrayhamilton** [comment]
I am only using these packages in a browser context (after installing them via npm), so I'm not the best person to ask. But `npm test` does yield positive results on my machine on Node.js 6.2.1.

**Comment by kof** [comment]
then its most probably just bumping up the range
