### ISSUE TITLE
there is no possibility to add the generated rule in sheet

### ISSUE THREAD

**Issue by b2whats** [jsstyles/jss#253]
@kof 
```js
const sheet = jss.createStyleSheet({}, options)
....
const newRule = jss.createRule(name, rule)
// we need re-create the rule
sheet.addRule(name, rule) 
```

but I would like to insert a rule into the sheet
```js
const newRule = jss.createRule(name, rule)
sheet.addRule(newRule) 
```

**Comment by kof** [comment]
Ok it seems like a .sheet property is not available when element is detached, so basically we can't use addRule on detached style sheet.

**Comment by kof** [comment]
so the question now is how to workaround this for the user layer.

**Comment by kof** [comment]
Also it has never been needed so far, it is the first time we stumbled over this issue.

**Comment by kof** [comment]
The question is: do we really need a possibility to add rules to a detached style sheet?

**Comment by kof** [comment]
If we really need this, I see 2 possibilities how to fix it:
1. schedule adding rules up to the moment when sheet will be attached and add them then
2. redeploy the sheet once it needs to be attached all together with the new rules

**Comment by kof** [comment]
fixed and released: when adding rules in a detached state, sheet will be redeployed once user attaches it.

**Comment by kof** [comment]
Sorry I mised up this issue with the #252

**Comment by kof** [comment]
The question here is why do you want to use this? I realize it seems intuitive to you what you suggest, but knowing the code base I may cause side effects. And I don't to add this feature without a good reason.

**Comment by kof** [comment]
Waiting for a practical use case for this feature request. @b2whats

**Comment by kof** [comment]
Closing this for now, @b2whats please reopen it once you have more input.
