### ISSUE TITLE
Registered functions with jss.use() are being called twice (4.0.X)

### ISSUE THREAD

**Issue by poupougnac** [jsstyles/jss#258]
Is this an expected behavior ? This does not happen with 3.x.x.

```
import jss from 'jss'

jss.use((rule) => {
  console.log(rule.className)
})

let sheet = jss.createStyleSheet({
  container: {
    transform: 'translateX(100px)'
  }
})
console.log(sheet.toString())
```

![screenshot at 2016-07-05 10 43 24](https://cloud.githubusercontent.com/assets/318256/16578937/8aae75e8-429d-11e6-9e03-066e9649b78b.png)

**Comment by kof** [comment]
it should be a bug, just wrote a test to reproduce it, will be fixed in the evening.

**Comment by kof** [comment]
fixed and published
