### ISSUE TITLE
Media queries doesn't work if you don't have non media query styling as well.

### ISSUE THREAD

**Issue by iamrane** [jsstyles/jss#259]
I have this jss code:
```
'@media only screen and (min-width: 720px)': {
	content: {
		padding: '0 32px 16px 64px'
	}
},
'@media only screen and (max-width: 720px)': {
	content: {
		padding: '0 16px 16px'
	}
}
```

and its compiled to
```
@media only screen and (min-width: 720px) {
  .content--jss-0-40 {
    padding: 0 32px 16px 64px;
  }
}
@media only screen and (max-width: 720px) {
  .content--jss-0-42 {
    padding: 0 16px 16px;
  }
}
```

How come its different class names. I guess they should be the same. The result is that the last one works, but not the first one.

**Comment by kof** [comment]
you can't use same key in objects twice.

**Comment by iamrane** [comment]
Ah now I see the problem. This is actually a bug. If I don't have any styling for content in non media query. The media query styling won't trigger.

**Comment by iamrane** [comment]
## This doesn't work
```
'@media only screen and (min-width: 720px)': {
	content: {
		padding: '0 32px 16px 64px'
	}
},
'@media only screen and (max-width: 720px)': {
	content: {
		padding: '0 16px 16px'
	}
}
```

### But this work

```
content: {
   border: '1px solid black'
},
'@media only screen and (min-width: 720px)': {
	content: {
		padding: '0 32px 16px 64px'
	}
},
'@media only screen and (max-width: 720px)': {
	content: {
		padding: '0 16px 16px'
	}
}
```

**Comment by kof** [comment]
again, don't use same property twice in object literals ...

**Comment by kof** [comment]
I have added a  test exactly for this case, works for me.

**Comment by iamrane** [comment]
Hmm okey.
I don't use the same key twice. And it works when I add content:'' on content outside media query. (I used content:'' because it doesnt do anythingon non absolute elements. When I add that it works.

And it also worked before when I used css modules. But when Im switching to jss i need to add content:''.

I still think this is a bug. But I found a hack around it.

**Comment by kof** [comment]
> I don't use the same key twice.

You do, by key I mean `@media only screen and (min-width: 720px)`, this media query is a key in an object literal.

**Comment by kof** [comment]
Also pro tip: always look at the generated css in the head, it gives you the full picture of what's been generated.

**Comment by iamrane** [comment]
I looking in the genrerated head. And the key is not the same. There is MIN-width and MAX-width

**Comment by kof** [comment]
Oh, I misread that min/max.

**Comment by kof** [comment]
I think I understand now the issue, need to add a test.

**Comment by kof** [comment]
Also probably #257 will fix it.

**Comment by kof** [comment]
added a test, on master it is already fixed

**Comment by kof** [comment]
now jss 5 is released, let me know if you still have problems after upgrading.
