### ISSUE TITLE
Is it possible to extract the generated css into a file?

### ISSUE THREAD

**Issue by ads1018** [jsstyles/jss#260]

**Comment by kof** [comment]
Yes, it is sheet.toString() > your-file.css

**Comment by kof** [comment]
also see ssr example https://github.com/jsstyles/examples/tree/gh-pages/react-ssr

**Comment by ads1018** [comment]
Thanks for pointing that out! How would you go about piping sheet.toString() to a css file using webpack?

**Comment by ads1018** [comment]
Extracting the css into it's own file brings obvious performance advantages since the browser can then cache that resource. It would be great if there was a section in the docs that explained how to achieve this with something like webpack :) I'd submit a pull request but I'm not sure where to start.

**Comment by kof** [comment]
This is not about jss, but about webpack, feel free to learn how to create webpack loaders and also you might be able to find one on npm.
