### ISSUE TITLE
getRule when using rule with nested properties

### ISSUE THREAD

**Issue by bassment** [jsstyles/jss#261]
**First of all thanks for great library!**

**_But I have little problem when I have such code:_**

I'm using 'jss-nested' npm module:

`const jssNested = require('jss-nested').default;`

`jss.use(jssNested());`

`const sheet = jss.createStyleSheet({
  link: {
        '& a': {
            color: styles.link.color
        }
    }
}, {link: true})`

**_And i'm trying to get this nested 'a' tag rule, and to set new color to it like in Javasxript API docs:_**

`sheet.getRule('link a').prop('color', 'green')`

But this does not work, so I find the solution to get it using selector with hash:

`sheet.getRule('.link-3130816284 a').prop('color', 'green')`

This looks ugly and hardcoded, so i'm asking, maybe i'm missing something from the docs.

Thanks for help in advance! ;)

**Comment by kof** [comment]
It's nice that you assumed `sheet.getRule('link a')` would work, but it doesn't, also not documented this way. 

Can you use  a regular rule instead?

**Comment by bassment** [comment]
Thanks! I setup it with regular rule and it works like I've expected. 
**_I used it like this:_**
`sheet = jss.createStyleSheet(links, {link: true, named: false}).attach();`
`self.sheet.addRule('.link a:hover', linkStyles.hover);`
**_And setting new color:_**
`self.sheet.getRule('.link a:hover').prop('color', 'green')`

**Comment by kof** [comment]
By regular rule I ment a rule without nesting, sorry, but this is also a way. However you are using a global class name and you loose the advantage of namespacing.
