### ISSUE TITLE
Do you have some caching/matching inside?

### ISSUE THREAD

**Issue by DeWenS** [jsstyles/jss#263]
Inside React i've created 2 components with styles. Each one have same classnames: 
component 1: 
```javascript
styles: {
  block: {
    flex: 1
  },
  '@media(...)': {
    block: {
      flex: 2
    }
  }
}
```

component 2: 
```javascript
styles: {
  block: {
    flex: 1
  },
  '@media(...)': {
    block: {
      flex: 3
    }
  }
}
```

and they both will have same class and use only one of the '@media' (which were earlier)

**Comment by kof** [comment]
nope, they will have separate style elements and separate rules.
