### ISSUE TITLE
Add 'removeRule' method to JavascriptAPI

### ISSUE THREAD

**Issue by bassment** [jsstyles/jss#266]
Can I remove rule programmatically, if I don't need it anymore and don't want to keep unused style classes in my page's stylesheet?

I added the rule previously with sheet.addRule API. Whould be nice to see removeRule.
Do you support the removal?

**Comment by kof** [comment]
You are the first person who asks for that feature. I need to know the use case behind this request.

**Comment by bassment** [comment]
In my use case I created a list: `const linkList = ['black link`, green link', etc.] which change the class of the target link after I hover on one of list items.
I add jss rule like: `sheet.addRule('.link_01 a:hover', {color: 'red', background: 'blue})` if I hover on a first list item and so on.
So when I hover on another item I need to remove previous rule and add a new rule. If i do not do this, I will end up with several unused styles in my page's stylesheet when I just hover on several list items and just apply one at a time.

**Comment by kof** [comment]
This seems to be a use case for inline styles.

**Comment by kof** [comment]
Also if colors are static and finite, you can create styles with JSS for them and switch classes.

Use JSS where you would use CSS back in the days.

**Comment by bassment** [comment]
I used your library because I can add and change properties to the class dynamically. My previous use case has limitation that I can't add styles to the link inline. So I found your library to add dynamic styles to the class directly using rules. I just was wondering when looking on API, that add style to the class(add rule) exist while remove does not exist.

Anyway, it is not a huge pitfall in my use case, but anyway it looks logical for me to add 'remove' method if 'add' method in API exists.

**Comment by kof** [comment]
As soon as I hear a good use cse I will add it) Adding anything to the library without real life use cases behind it is a bad praxis.

**Comment by bassment** [comment]
I have a real pain without deletion functionality.
Will try to explaine my case better:
- User of the site can customize the styles of the element by himself, in this case inline css styles are set to the element he customly changed.
-  There are also global styles for these elements, which are set with classes.
- Right now i'm working on a feature where the user can change all the elements globally from one place. So I can't change inline styles, since they are custom and should be reserved unchanged.
This could be done by:
1) Setting new classes manually for every element(which is unreal in my case)
2) Or change to the class dynamicaly(since it's SPA) with javascript.

So I found your library, because it gives the possibility to write to classes dynamically, like:
```javascript
sheet.addRule('.blockquote_01', {color: 'green'})
```
Now I have the problem deleting this stylesheet from the page. Since I have several classes like '.blockquote_01', '.blockquote_02' etc. which user changes dynamically. The page will end up with several global classes existing in stylesheet of the page, which are rewriting each other. So I need the deletion method, to handle such problems.

I belive the screenshot will give some light to the problem:

![deleterule](https://cloud.githubusercontent.com/assets/12432960/17138399/c2e4e530-5348-11e6-88e1-fc6dfad63d54.png)

**Comment by kof** [comment]
implemented a deleteRule method, published, feel free to reopen if it doesn't work.

**Comment by kof** [comment]
https://github.com/jsstyles/jss/blob/master/docs/js-api.md#delete-a-rule-from-an-existing-style-sheet

**Comment by bassment** [comment]
Thanks for implementing! Have cleaned my stylesheets successfully, didn't spot any bugs yet.
