### ISSUE TITLE
Element queries.

### ISSUE THREAD

**Issue by kof** [jsstyles/jss#267]
Let's discuss how element queries could be implemented.

**Comment by tizmagik** [comment]
There's https://github.com/joeybaker/react-element-query -- the syntax of which is awkward, but may be a source of inspiration?

Also, I'm not sure if element query support makes sense to support in JSS? Maybe as a plugin or something, so it's an opt-in kind of thing. My 2 cents.

**Comment by kof** [comment]
Just found out that element queries are not part of any standard yet. Puhh....

**Comment by kof** [comment]
I don't see what we could do here ...
