### ISSUE TITLE
Implement method to add object with styles to rule

### ISSUE THREAD

**Issue by bassment** [jsstyles/jss#268]
For now I can only `sheet.getRule('a').prop('color', 'green')` 
But in my case I have an object with 2 properties that I need to add.
So I need to:
```javascript
for (let prop in linkStyles.default) {
    sheet.getRule('a').prop(prop, linkStyles.default[prop]);
}
```
Here `linkStyles.default` is an object with styles like: 
`{ color: 'green',backgroundColor: 'red'}`

Would be nice to see for example `.set `method so I can do like this:

```javascript
sheet.getRule('a').set(linkStyles.default);
```

**Comment by kof** [comment]
Why don't you use addRule in this case?

**Comment by kof** [comment]
sheet.addRule('a', {color: 'green', background: 'red'})

**Comment by bassment** [comment]
Thanks! It was not obvious for me at first. that it will just override existing rule. I changed my code to use addRule and it looks more cleaner now. Just one question, will it create new hash for an 'a' rule when I override the styles with addRule method?

**Comment by kof** [comment]
not sure what you mean by your last question.

**Comment by bassment** [comment]
```javascript
var jss = require("jss").create();

var sheet = jss.createStyleSheet({
    button: {
        color: 'green',
        backgroundColor: 'red'
    }
}).attach();

var firstButton = sheet.getRule('button');

sheet.addRule('button', {color: 'red', fontWeight: 700});

var secondButton = sheet.getRule('button');

console.log(firstButton.className, secondButton.className);
```
I tested myself, was wondering if murmurhash changes hash when using addRule instead of changing props directly.

Nevermind ;)

**Comment by kof** [comment]
I think current logic leads to an overwrite of the first rule and class name is taken from the map. Not sure though because this case is not covered by tests.
