### ISSUE TITLE
CSS to JSS online tool

### ISSUE THREAD

**Issue by umidbekkarimov** [jsstyles/jss#269]
Similar to [htmltojsx](http://magic.reactjs.net/htmltojsx.htm)

**Comment by kof** [comment]
I think normal CSS doesn't compiles well to  jss with namespaces and high level of code reuse. It can be easily compiled only to global jss with `named: false` option and we don't want to encourage that, right?

**Comment by kof** [comment]
So this idea makes sense only if we find ways to convert css to a high quality jss, [jss cli](https://github.com/jsstyles/cli) is a good place for that.

**Comment by kof** [comment]
We may consider to compile at least parts that work, not a fully functional 1:1 compilation.

**Comment by umidbekkarimov** [comment]
> we don't want to encourage that, right?

True, but main reason of this tool is to help with migrating from css to jss faster.

Like `htmltojsx` will help you to create plain component that you can transpile and run in your browser, after that you have to make lot of changes to make your component work.

So I think it's enough to convert to `jss` with `named: false` to just make it work, and after that developers will have to make all selectors named and get rid of `named: false` for their own sake
___
It's always easier to find some ready code in html+css, `htmltojsx` helps to convert big amount of `html`, so we need something to convert `css` 
___

> jss cli is a good place for that.

I totally missed that tool!

**Comment by umidbekkarimov** [comment]
Tried `jss-cli`, and it gave me all I wanted!

So I think that it's enough to make it as online tool

**Comment by kof** [comment]
You might be right, a fat warning to not to use it as-is would be probably enough, also a good place for this would be probably to add it to the current [repl](https://jsstyles.github.io/repl/) and here is the issue #166

**Comment by kof** [comment]
Also created a new task for repl #270

**Comment by kof** [comment]
Also the reason you didn't find the cli tool is probably it somehow tropped out of documentation.

**Comment by kof** [comment]
updated readme.md
