### ISSUE TITLE
Add ci

### ISSUE THREAD

**Issue by kof** [jsstyles/jss#27]

**Comment by joshgillies** [comment]
I wonder, would porting the tests from qunit to something like tape help getting this happening? As an aside it would be nice to integrate saucelabs or similar to run test agains multiple browser environments.

**Comment by kof** [comment]
I think its possible with qunit too.

**Comment by kof** [comment]
Also I am open to migrate to mocha/expect.js

**Comment by kof** [comment]
duplicate of #114
