### ISSUE TITLE
Dynamic values for css properties in React

### ISSUE THREAD

**Issue by igorpreston** [jsstyles/jss#273]
Hello,

I am working on the project that requires to define css property values based on props that React component receives from API.

Example
`const styles = {
 widget: { width: props.width } }`

Previously it was accomplished using const styles defined inside render() method, where React props are accessible.

However, right now I should use useSheet react decorator to define it out of the scope of React component class, therefore I can't access react props.

Any suggestions on how to handle that problem?

**Comment by kof** [comment]
One way is continue using inline styles for dynamic values.
