### ISSUE TITLE
Not Working with postcss-js Anymore

### ISSUE THREAD

**Issue by muratgozel** [jsstyles/jss#274]
I am using a small pre-compile script to process jss stylesheets with postcss-js plugins before building the app. Output of the compiling is autoprefixed jss stylesheets. As of version 5, i lost this functionality. I only use postcss autoprefixer plugin right know but it would be nice to see jss working fully compatible with postcss plugins. Especially autoprefixer.

This is the salt jss stylesheet i wrote:
```javascript
...
  intro: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center'
  },
...
```

And this is compiled stylesheet by postcss-js plugin:
```javascript
...
	intro: {
		display: [
			'-webkit-box',
			'-ms-flexbox',
			'flex'
		],
		WebkitBoxOrient: 'vertical',
		WebkitBoxDirection: 'normal',
		msFlexDirection: 'column',
		flexDirection: 'column',
		WebkitBoxAlign: 'center',
		msFlexAlign: 'center',
		alignItems: 'center',
    }
...
```

All properties rendered correctly by jss except display property. It is rendered as
`display: -webkit-box, -ms-flexbox, flex`
which is invalid.

Any suggestion would be appreciated?

Also you can find the precompile script here: https://gist.github.com/muratgozel/e3ca2c08f74c9cb6eb7314e3088edb77

**Comment by kof** [comment]
Please create an issue at postcss-js, see the changelog, major versions has been released with breaking changes.
