### ISSUE TITLE
attaching stylesheet vs. creating style tag

### ISSUE THREAD

**Issue by serapath** [jsstyles/jss#44]
I'm a bit new to this and maybe the question is kind of pointless, but i read in another place, that using jss in components makes it hard to use server side rendering. My first thought is, that the styling created by jss can be added in a <style> tag. Wouldnt that enable to create a server response that works?

**Comment by kof** [comment]
I think what you read is https://github.com/jsstyles/react-jss/issues/2

I just wrote an answer to this, hope it makes sense to you, otherwise feel free to reopen this issue.
