### ISSUE TITLE
Support conditional rule groups for named styles

### ISSUE THREAD

**Issue by kof** [jsstyles/jss#46]
As a result of https://github.com/jsstyles/jss/pull/45

We need to support conditional rule groups like @media in named style sheet https://developer.mozilla.org/de/docs/Web/CSS/At-rule

One proposal would be to write it like this

```
{
    myName: {
        condition: '@media (min-width: 1024px)',
        color: 'blue'
    }
}
```

Another proposal

```
{
    button1: {
        color: 'red'
    },
    '@media screen and (min-width: 768px)': {
        button1: {
            color: 'green'
        },
        button2: {
            color: 'blue'
        }
    }
}

```

**Comment by kof** [comment]
The reason for a different syntax is that we need all rules to be accessible via sheet.getRule and sheet.classes.myRule ... because thats the point of named style sheets.

**Comment by markdalgleish** [comment]
FWIW, on my initial reading of the docs, I got the impression that you could use media queries with namespaces based on the first JSS syntax example.

**Comment by markdalgleish** [comment]
Whether that means the API is confusing, the readme is confusing, or I'm just generally confused due to my own issues, I don't really know.

**Comment by kof** [comment]
yep, this example was initially without using named style sheet. After I changed named style sheet to be default and changed the example, @media part of it became invalid, thats why I have removed it for now until we implement it right.

**Comment by kof** [comment]
So confusion is because of this wrong example.

**Comment by markdalgleish** [comment]
My completely uninformed opinion is that you should be able to write what basically looks like CSS and it should just work, even if you used namespaces.

**Comment by kof** [comment]
Ideally yes, but in the real world namespaces mean we need to have a common scope for them. In case of conditional group rules they kinda introduce a new scope. So we need to break CSS compatibility when using named styles in this case to have just one scope per sheet.

**Comment by markdalgleish** [comment]
/s/opinion/assumption

**Comment by kof** [comment]
shouldn't be a big issue though, because there are not much conditional group rules, its just @media and @supports which is probably not used.

**Comment by kof** [comment]
another possibility would be to allow conditional group rules per style sheet.

**Comment by kof** [comment]
So that all rules within one style sheet are within @media condition.

**Comment by kof** [comment]
this would make 100% consistency with css but will force you to write separate sheets for this. Maybe not the worst option.

**Comment by markdalgleish** [comment]
The point I seem to have missed is that you can't override a namespace like you can with a selector when doing responsive design. Is this correct?

**Comment by kof** [comment]
Correct right now. But what if we allow this? And treat all declarations within a conditional group rule as an override if such a rule exist, if not - it will be added? May be also not bad at all.

**Comment by markdalgleish** [comment]
Makes a lot of sense to me. IMO the principle of least surprise would suggest you should be able to override just like normal CSS, otherwise this is just going to trip more people up.

**Comment by markdalgleish** [comment]
I assumed that namespaces just meant that you could allow JSS to generate class names for you, but otherwise allow me to just write CSS with a JSON syntax, at-rules and all.

**Comment by kof** [comment]
there are 2 basic ideas:
1. as you said - generated classes
2. access to the rules from javascript

The last point could become less intuitive if we start overriding rules, but maybe its not that important there.

**Comment by kof** [comment]
In terms of implementation details: a rule can become a container rule with subrules which have conditions. But at the end it should render to css  we expect.

**Comment by markdalgleish** [comment]
On the question of accessing the rules from JavaScript, maybe it would look something like this:

```js
sheet.getRule('myName');

//returns:
{
  color: 'red',
  '@media screen and (min-width: 768px)': {
    color: 'green'
  },
  '@media screen and (min-width: 1024px)': {
    color: 'blue'
  }
}
```

That would be the least surprising to me. Would that cause any issues? What are your thoughts on this API?

**Comment by kof** [comment]
this structure looks strange because @media conditional is on the same level as property names.

**Comment by kof** [comment]
getRule returns a Rule instance anyways ... I was thinking forward about getRule('...').toJSON()

**Comment by kof** [comment]
maybe toJSON should have an option for returning declarations only or with conditionals.

**Comment by kof** [comment]
I think this is the best syntax.

```javascript
{
    button1: {
        color: 'red'
    },
    '@media screen and (min-width: 768px)': {
        button1: {
            color: 'green'
        },
        button2: {
            color: 'blue'
        }
    }
}
```

Will try to implement something.

**Comment by kof** [comment]
Hmm another issue with this syntax is that its numeric values can't be easily constants, by nature of object properties.

**Comment by kof** [comment]
Is this actually an issue?


```javascript
var SOME_CONSTANT =  768

var rules = {
    button1: {
        color: 'red'
    }
}

rules['@media screen and (min-width: '+ SOME_CONSTANT+'px)'] = {
        button1: {
            color: 'green'
        },
        button2: {
            color: 'blue'
        }
}

```

**Comment by markdalgleish** [comment]
I can definitely see that becoming a bit annoying.

However, I still really appreciate the fact that it's a totally guessable format. I imagine most people, if asked to define CSS with media queries using JSON, would produce something similar.

Plus you could easily build some helpers to generate this format for you, if you feel the need.

**Comment by zimok** [comment]
Also, I think that it should be possible to extend rules with at rules in it.
What about this:

    var mixin = {
        '@media (min-width: 480px)': {
            display: 'block'    
        }
    }

    var rule = {
        extend: mixin
        background: '#ccc'
    }

Would be achievable? It's something that has more to do with extend plugin, or it's better to discuss it here?

**Comment by kof** [comment]
@zimok lets talk about it separately after we have a good working @media solution.

**Comment by zimok** [comment]
@kof yes, it makes sense

By the way, talking about @-selector rules, I believe in this case a special prop keyword, like  `condition`, would not be that weird, even if it's something completely unknown in css world – but, otherwise, what would be the benefit of using a pre-processor, if we can't keep things small and DRY?

Plus it would make the code more readable and smaller, avoiding repetitions (compare it to the alternative solution where you have to repeat the name of the rule every time within an @-rule).

I'd definitely prefer a special keyword against an over-nested, repeating structure, but that's a matter of personal style.

Eventually, I think we should also find a solution for using @-rules with named stylesheets.

I can put some tests and see what happens.

**Comment by artin-phares** [comment]
@kof How things going with this?

I would really appreciate @media support in such form
(your second proposal for API looks prettier for me btw.)

I know with 'jss' we can create several stylesheets with different media queries.
```
jss.createStyleSheet({_rules1_}, {media:'_query1_'}}).attach()
jss.createStyleSheet({_rules2_}, {media:'_query2_'}}).attach()
```
But I'm using 'react-jss' and we can create component with one stylesheet only, right?
```
useSheet(ReactComponent, {_rules_}, {media:'_query_'})

**Comment by kof** [comment]
I am on it, should be ready next week.

**Comment by kof** [comment]
its finally landed, please try it out, would love your feedback

**Comment by artin-phares** [comment]
@kof Great! JSS works as expected.

But I have a question regarding to 'react-jss'.
I have following jss definition:
```
  css: {
    externalRule: {
      'border': '1px solid red'
    },
    '@media print': {
      externalRule: {
        'border': '5px dashed black'
      },
      subRule: {
        'font-weight': 'bold'
      }
    }
  }
```

And in <code>this.props.sheet.classes</code> I got:
<code>{externalRule: "jss-0-2", @media print: undefined}</code>

My expectation is:
<code>{externalRule: "jss-0-2", subRule: "jss-x-x"}</code>
I.e. do not have @media and do have subRule there.

I guess this happens because 'react-jss' do not know about subrules yet.
What do you think? Should I forward this to 'react-jss' repo as an issue?

**Comment by kof** [comment]
thanks for the report,

1. removed @media from classes map
2. subrules from @media are designed as overwrites, if you want to access it via classes, define it in the main object

**Comment by artin-phares** [comment]
@kox yep, do not see <code>@media</code> in <code>classes</code> anymore.
Subrules overwrite behavior is not something obvious imho, but I do not see cases where it is going to be a blocking issue, though user always can add empty subrule at the top level to get it work...
Thanks!

**Comment by kof** [comment]
Yep, lets see if someone will stumble over it.

**Comment by kof** [comment]
closing for now, if something comes up feel free to reopen.

**Comment by kof** [comment]
Look whats possible with ES6

```javascript
const WIDTH = 700
{
    button: {
        color: 'red'
    },
   [ `@media screen and (min-width: ${WIDTH}px)`]: {
        button1: {
            color: 'green'
        },
        button2: {
            color: 'blue'
        }
    }
}
```

Will try to implement something.
