### ISSUE TITLE
Plans to support node above v0.8 ?

### ISSUE THREAD

**Issue by antoniobrandao** [jsstyles/jss#47]
jss wasn't working for me, when I attempted to update it I noticed this:

npm WARN engine jss@1.0.4: wanted: {"node":"0.8.0"} (current: {"node":"0.10.33","npm":"2.4.1"})

Are there plans to support node above v0.8 sometime soon? I'm using something else to achieve the same goal at the moment, but I would prefer to use jss, I like how it works.

Cheers

**Comment by kof** [comment]
already fixed, just waiting for the next release

**Comment by kof** [comment]
strict 0.8.0 was kinda stupid ...

**Comment by antoniobrandao** [comment]
Fastest reply ever. Thanks !!

**Comment by nkbt** [comment]
Not published to NPM yet. Still having same warning for jss@1.0.4

**Comment by kof** [comment]
published.

**Comment by antoniobrandao** [comment]
:cocktail: :tropical_drink:
