### ISSUE TITLE
Falsy value does not permit valid 0

### ISSUE THREAD

**Issue by urbantumbleweed** [jsstyles/jss#51]
Prop should be able to have a value that is a string or number.  Currently, if the value is falsy then the prop does not receive a value.

The evaluation should permit the value 0.

**Comment by kof** [comment]
you mean something like {zIndex: 0} would not be accepted?

**Comment by kof** [comment]
Ok the issue is in the .prop method. I would change it to `if (value != null)`

**Comment by kof** [comment]
published
