### ISSUE TITLE
Parse existing stylesheet

### ISSUE THREAD

**Issue by barneycarroll** [jsstyles/jss#53]
I realise this is aiming very low compared to the truly awesome use case scenarios JSS caters for. However, there's the potential here for making an old nightmare in front-end hackery far more pleasant.

Namely, parsing and modifying a pre-existing stylesheet.

My actual scenario: I'm using [Auth0-lock](https://github.com/auth0/lock) and they have wrapped some awesome functionality in a UI with an incredibly heavy-handed style implementation. They inject a `style` element into the head that's chock full of rules with multiple ids, wildcard selectors and `!important` properties. Modifying the appearance is a nightmare because you have to write *even heavier* rules just to compensate for each and every one of their own. As a result, you loose all the flexibility of your existing style strategy. If I could just reach in and delete the offending rules I could do away with some of their worst crimes while retaining the legitimate stuff. This sounds like a ludicrous situation (and it is!) but compensating for heavy-handed 3rd party widgets is a pretty common scenario in my experience.

The other use case for this is as a stepping stone in between an existing application's styles strategy and full-blown JSS-from-the-ground up. Say my current application uses SASS Bootstrap all over the place and I don't want to have to re-write the whole thing, just extend some style rules dynamically. This feature would allow people to get into JSS progressively without having to ditch the whole concept of pre-compiled or static CSS.

What do you think?

**Comment by kof** [comment]
1. parsing existing styles is definitely out of scope for jss
2. it integrates already well with any existing css framework. You can use other classes + jss classes ... 
3. In your use case I would not go and modify those external styles as it will break any  time. Maybe generating inline styles from jss would be a more robust way in order to override styles from 3rd party ...

**Comment by barneycarroll** [comment]
> 1. parsing existing styles is definitely out of scope for jss

Fair enough. Might work on a plugin to adapt this functionality from the [Box9/jss](https://github.com/Box9/jss). I'll keep you in the loop.

> Maybe generating inline styles from jss would be a more robust way in order to override styles from 3rd party 

Not really. Continuously overriding with heavier rules is a historic problem for badly written static CSS. You get less and less control at more and more expense, and end up having to write a huge amount of code to to very little. In these scenarios, JSS doesn't really add anything to the mix – it's more an example of how you wouldn't even have the problem in the first place if you had used JSS from the ground up and could rely on flexible and dynamic styles. 

> In your use case I would not go and modify those external styles as it will break any time

Yes, the whole use case is a hack. I can easily understand the attitude that this is not a problem JSS aims at solving :)

**Comment by kof** [comment]
:+1:

**Comment by barneycarroll** [comment]
> Might work on a plugin to adapt this functionality from Box9/jss. I'll keep you in the loop.

 Amend: Might work on a plugin to adapt this functionality from [JSS's CLI](https://github.com/jsstyles/jss#convert-css-to-jss) which already performs pretty much this task. Ironically with a little hackery I can already get JSS to do this without 3rd party code.

**Comment by kof** [comment]
jss cli is for static parsing. You can create a parser for runtime which generates jss definitions and pass them to jss.
