### ISSUE TITLE
Display minified / gzipped size in Readme

### ISSUE THREAD

**Issue by diingo** [jsstyles/jss#55]
JSS says it's small. kb numbers would be great to know

**Comment by kof** [comment]
I won't maintain kb numbers ... in the documentation manually, you might want to send me a PR which calculates on build and replaces in readme :)

**Comment by mindeavor** [comment]
As a developer evaluating JSS, it certainly looks interesting, but I want to know how much it's going to cost in terms of file size. Even if not 100% accurate, a rough kb estimate makes these decisions much easier for new adopters.

**Comment by kof** [comment]
you see the minified file in the dist ...

**Comment by mindeavor** [comment]
Yes, and of course I could also download it and run gzip in the command line myself if I wanted to put in that much effort. What I'm suggesting is to add a couple numbers to the readme for the benefit of the project. The idea is you directly show people important, relevant information, as opposed to making them dig around for it. It's a small, but effective marketing tactic.

**Comment by kof** [comment]
ok lets add appr number in kb ...
