### ISSUE TITLE
Bench completes around the three seconds mark

### ISSUE THREAD

**Issue by daleeidd** [jsstyles/jss#57]
I just tried the [JSS bench](https://jsstyles.github.io/jss/bench/bootstrap/jss.html) and I got…

> domcontentloaded: 2997ms

GitHub sets the `Content-Type` to `application/octet-stream` which, from previous experiences, can make it extremely slow to process. It isn't consistent though; quite a few times I got below the one second mark.

I just thought I would give you a heads up.

**Comment by kof** [comment]
yeah this test is very inaccurate, needs to run multiple times to get something average ... I didn't find a way to do this automated.

This test shows real life code in a closest possible to real setup to compare how fast jss renders compared to pure css.

**Comment by kof** [comment]
On my mb air 2011 I get 150-300ms results

**Comment by kof** [comment]
in chrome
