### ISSUE TITLE
Fully re-usable components

### ISSUE THREAD

**Issue by serapath** [jsstyles/jss#59]
A component consists of:
* html
* jss
* javascript

If I write a component, it's very likely, that it'll use `assets` (may that be `fonts`, `images`, `videos`, `audio`, or something else). Now let's assume I create a component `fancy-menu`.

So I do:
`$> npm install fancy-button --save`

My current component is called `special-page`.
Now in my current component, I'd like to use:
```js
var fancyButton = require('fancy-button');
var menustructure = require('./menustructure.json');
var container = document.querySelector('#menuvar');
var remoteControlAPI = fancyButton(container, menustructure);
```
This will add the fancy-menu to the dom container initializing it with whatever my `menustructure.json` contains. In addition, I return some kind of API, with which my current component can "remote control" the fancy-button.

So far so good. The problem is, the `HTML` and maybe the `CSS/JSS` of my `fancy-button` component use **assets**.

I continue now to build my `special-page` with:
`$> browserify specialpage.js > bundle.js`
When I load my `index.html`, it fails to load all the assets contained in the installed `fancy-button` component, because they are somewhere nested in `node_modules` and so the asset paths are wrong.

Is there a solution for that already? If not, how to approach this problem?

**Comment by kof** [comment]
I am not sure how is this related to jss. Its a build system issue. Maybe you should try browserpack ....

**Comment by serapath** [comment]
It's true, but there are existing solutions that check `HTML` and fetch asset paths and copy out assets from all the `npm dependencies` into a build folder + replace the `asset paths` to that build assets folder.
This also exist for `css` using [atomify](http://github.com/atomify/atomify).
The package that does it for `HTML` is called [resrcify](https://github.com/bclinkinbeard/resrcify) and for css its `rework-css` and `rework-npm`.

I have a working solution for components using `atomify`. If I want to switch my components to use `jss`, i need to figure out how to deal with assets and because the feature is in `components` its kind of important. Do you know about a solution?
I'd prefer browserify over webpack

**Comment by kof** [comment]
well I save jss declarations in js files, so there is no need for extra loaders, its just javascript. Or I don't really understand the issue you are facing

**Comment by barneycarroll** [comment]
@serapath so JSS allows style to be fully componentized. In combination with some kind of component-based MVC framework, this allows structure, behaviour and *appearance* to become entirely manageable as discrete Javascript notation.

The question that remains is how to deal with multimedia.

In my mind, there is no real case for a component that has a predetermined video which must be part of the component itself — in any realistic scenario you would want to specify the source of that video at runtime: the component should accept an argument to define that.

With images, it's more complicated. Some stylesheets rely on discrete image resources, so a componentized style declaration needs to take care of that. We have some options:
* base64 encoding allows us to store any medium as a string representation which can be referenced by Javascript in memory. This is similar to what Google used to do with Google.com for mobile browsers 3 years ago.
* SVG as DOM notation. This means we can forget about the style aspect and simply invoke new components which are rendered to DOM

In any case, we need an idea of what the problem is and how we want to solve it before we say this is an issue with JSS

**Comment by serapath** [comment]
There might be "icon fonts" that i use in a component, and there are probably many more use-cases.
A video could also be some ambient moving background ... it really depends, but there are many use cases for sure.

**Comment by kof** [comment]
I think most of the time you won't bundle those things with components.

**Comment by kof** [comment]
why is it actually a problem to hav a separate package for an icon font. This package could bring its own jss with font-face declaration, so you require this file from your components and build system ensures you to use the same file everywhere.

**Comment by barneycarroll** [comment]
@serapath maybe you could illustrate an idea of a component that includes these things but is not yet possible, and we could work towards it? I appreciate the concept, but it's difficult to imagine a solution without a concrete problem.

**Comment by serapath** [comment]
For example, i worked for a company that has a large web app and they want to re-use a button all over the place. The button comes in certain variants and states.
"fancy", "normal", "small", "big", "normal" .... they include different gradients, colors and sizes, but the most important part is the variants:
"download", "signup/signout", "send/submit", "confirm/cancel", "disabled", ...and a lot more.

They use their button in different projects, internal and external and include their "corporate branding" their. So those different states are supported by different icons (e.g. loading spinner, save symbol, submit symbol, ....)

**Comment by serapath** [comment]
And that's just a very very basic simple component. Whole websites can be components (a blog as a component) ... you will add your pictures or change the theme with some parameters, but the rest is included. It's a vital feature to build bigger components from smaller components.
Otherwise, again, those assets become global configuration, which sometimes might be what you want, but than just offer: ** DEPENDENCY INJECTION ** , but if not provided, then the component falls back to the **built-in default assets** :-)

**Comment by kof** [comment]
Its possible. But in real life it you will get a potential overhead. Imagine every button will bring its own font or icon ... even if its basically the same.

**Comment by serapath** [comment]
Not necessarily. Because the referenced asset paths included in css or html or javascript might get switched for injected ones (maybe through command line parameter or config files or i dont know what).
So applying browserify with the right transforms might only end up including the assets actually used.


Using [atomify](http://github.com/atomify/atomify) I'm adding my asset paths to default variables. When I use the component, i specify alternative paths in my theme.css, which the rework preprocessor will pick up and insert everywhere. Those paths will then be used to copy the actually used assets to a build folder and replace the paths in the bundle.css with those.
For more details: http://serapath.github.io/atomify/#/4

**Comment by barneycarroll** [comment]
@serapath I don't get it — JSS offers a method for modular style architecture. You're using an alternative method for doing that, but you're opening an issue on JSS for doing stuff unrelated to styles… what's the expectation here?

**Comment by serapath** [comment]
If i write a component, having an `html file` and a `javascript file` and my styles written in `jss` and i want to include assets, like `icons`, `fonts`, `images`, `videos` or `audio files` or i dont know what, and then import the component in a different component using:
```js
var myJssComponent = require('myJssComponent');
```
And in the end using `browserify` to bundle everything up, how would the above mentioned asset paths still be correct? How do you solve that problem with jss?

I can imagine to export some kind of jssConstructor from myJssComponent, where I can inject asset paths, so that would be fine, but if i do not inject anything, i'd like to use the fallback, thus assets that belong to the myJssComponent in the first place and here i have trouble understanding how the asset paths could stay valid, because you never know how deep myJssComponent gets nested into the node_modules/ folder.

@barneycarroll can you explain more in detail how JSS offers a method for modular style architecture that solves this problem or point me to some reading material?

**Comment by nkbt** [comment]
Everything is already fully bundleable and modular. With Weback.
My components use JSS and I always do `backgroundImage: `url("${require('asdf.png')}")`. All assets are properly embedded by Webpack.
You can easily do a build for your module only and publish it on npm with pre-build stuff, which will have all base64-encoded inside the component itself. One file which will have all things in it. Fully portable.

Correct me if I miss the point

**Comment by serapath** [comment]
Thats true, I can just inline all the assets, but this is always possible.
If you use assets multiple times, you will have them inline multiple times. The advantage of not inlining them would be to save some space.

**Comment by barneycarroll** [comment]
What kind of space are you talking about here? I'd be interested in how inlining stuff multiple times negatively affects user experience if that's what you're talking about.

**Comment by kof** [comment]
Yeah inlining would result in including base64 encoded images every time if you don't take care about it and put all those paths in one place and reuse them from there. But its actually not that hard.

**Comment by kof** [comment]
However you can't inline fonts as far as I know.

**Comment by nkbt** [comment]
@kof I do inline fonts as well. It's heavy though.

**Comment by barneycarroll** [comment]
What's the use case for a web component packing it's own fonts? I'm using Auth0 currently and I'm subclassing the module to remove the font declarations they've inserted. Modular CSS is awesome but chopping and changing core typography within a document is an idea that horrifies the designer in me.

**Comment by serapath** [comment]
@kof you can inline fonts, check out [font-store](https://github.com/CrocoDillon/font-store/)

For me, in abstract, the "perfect workflow" would include "self contained components", that come with default design/assets/logic/everything... (html,images,css,javascript,fonts,video,sound...)

Whenever I use them, I can "inject" replacements for the defaults.

Whenever i "build" my project, may that be with `browserify` or in other ways, I get a minimal build, that includes all the used `css, html, javascript & assets` that are used and does not waste space (or at least allows that option)

How to achieve this with `jss`. Even if it's currently not possible, I'd like to see if that is a planned feature for the future and in what way that could be added, so I can decide how to evolve my stack :-)

I'm sorry if my request came across as offensive. I'm very impressed with `jss` and I'm following the project for quite some time, because I really like the idea of controlling my styles from javascript.

**Comment by kof** [comment]
yeah seems like fonts can be base64 encoded and inlined same way as images.
