### ISSUE TITLE
Mixing local and global classes in the same selector

### ISSUE THREAD

**Issue by markdalgleish** [jsstyles/jss#60]
We're currently using [postcss-local-scope](https://github.com/markdalgleish/postcss-local-scope) to try and achieve similar goals to this project, at least at a high level.

In order to tame global selectors that are outside of our control, we allow local and global selectors to be mixed, for example:

```css
.local_class :global .transition-active-enter { ... }
```

It'd be great if there was a way to achieve this with jss.

**Comment by kof** [comment]
But why do you need it?

**Comment by kof** [comment]
give me a concrete example please

**Comment by markdalgleish** [comment]
After our discussion on Twitter, it looks like our specific use cases are covered.

**Comment by kof** [comment]
great! using globals within components is dirty anyways. Should be handled differently ...
