### ISSUE TITLE
cssToJss as a standalone module?

### ISSUE THREAD

**Issue by joshgillies** [jsstyles/jss#61]
I'm currently hoping to use JSS for a project; a part of my use case is taking existing CSS and converting it to JSS. I see there's a transpiler bundled with the CLI currently, but requiring it looks something like this:

```js
var toJSS = require('jss/bin/cssToJss')
```

Would it make sense to break this out into it's own module? Doing so could also ease the development of other *ToJSS transpilers.

**Comment by kof** [comment]
definitely, it was a quick and dirty solution for testing, only used in cli right now.

**Comment by kof** [comment]
if you are willing to send a pr, we can discuss the details

**Comment by joshgillies** [comment]
Alternatively, as it is kind of *core*, kind of! It could simply be exposed via a `jss.parse(css)` method?

My issue with the current implementation is the lack of default options. The way I'm using it I must set:

```js
var parseCSS = require('jss/bin/cssToJss')
var sheet = parseCSS(css, {
  pretty: false,
  export: 'module.exports = '
})
```

It'll otherwise error if options is undefined.

I'll submit a PR agains this repo to patch the above, and we'll discuss the finer points there.

**Comment by kof** [comment]
well its not a core because core is pure frontend ... it should really be a separate repository maybe jss-cli

**Comment by joshgillies** [comment]
Good point. So what we'll end up with would be repositories for `jss-cli` and `css2jss`?

**Comment by kof** [comment]
I think jss-cli is enough for now, when we add more converters and need to separate them for some reason, could still be done

**Comment by kof** [comment]
created cli repo, lets move the cli there.

**Comment by joshgillies** [comment]
Sounds good :+1:

**Comment by joshgillies** [comment]
Actually, that wont solve my initial issue. I'd still have to call:

```js
var toJSS = require('jss-cli/cssToJss')
```

If you can move cssToJss into whatever repo you see fit, I'll send a PR to add in default options, and some tests.

**Comment by kof** [comment]
I believe I missed the point, whats the issue you are trying to fix?

**Comment by joshgillies** [comment]
Sorry, to clarify:

The issue as I originally posted is that in order to require the cssToJss transpiler currently a third party must require it as follows:

```js
var toJSS = require('jss/bin/cssToJss')
```

Ideally as a third party I'd prefer to require the cssToJss transpiler via:

```js
var toJSS = require('css2jss')
```

or similar.

**Comment by kof** [comment]
oh its just about the path, you feel uncomfortable requirring something from bin dir?

**Comment by joshgillies** [comment]
that specifically yes :)

**Comment by kof** [comment]
require('jss-cli') is fine I think

/lib/cssToJss.js
/index.js
`exports.cssToJs = require('./lib/cssToJss')`

**Comment by joshgillies** [comment]
I guess the only issue there is that if all you require is the `cssToJss` functionality, you'd also get `"commander": "^2.6.0"` as an additional unrelated dependancy.

**Comment by kof** [comment]
yes, but shoudn't be that much an issue, we are serverside, right?

**Comment by joshgillies** [comment]
Good point! :smile:

**Comment by kof** [comment]
So do you like to send a PR  to the jss-cli repository?

**Comment by kof** [comment]
There is also another task for jss-cli #62 waiting to be implemented.

**Comment by kof** [comment]
we are done here, right?

**Comment by joshgillies** [comment]
Yup, thanks. :)
