### ISSUE TITLE
global version of jss.

### ISSUE THREAD

**Issue by trusktr** [jsstyles/jss#62]
It'd be super nice if the scripts section of package.json had a script using browserify or webpack to compile a standalone bundle to run in the browser that adds `jss` to the global scope. Some people could benefit from this right away in [certain scenarios](https://forums.meteor.com/t/stylus-css-vs-less-vs-sass/3752/29?u=joe) depending on their stack.

**Comment by kof** [comment]
You mean like loading jss + styles separately before everything else to let it style quickly the page without to wait for all other scripts?

**Comment by kof** [comment]
Kinda bundling feature, I think we can add it to jss-cli

**Comment by trusktr** [comment]
@kof Not quite, I meant something like https://github.com/jsstyles/jss/pull/63.
