### ISSUE TITLE
No way to do pseduo elements/nested elements?

### ISSUE THREAD

**Issue by nmn** [jsstyles/jss#67]
To my surprise, JSS doesn't seem to support psedo elements, or properly nested elements.
```
jss.createStyleSheet({
  x: {
    color: 'blue'
  },
  'x:hover': {
    color: 'green'
  }
}).toString()
```
produces:

```
.jss-1 {
  color: blue;
}
.jss-2 {
  color: green;
}
```

Clearly, the actual result should be:

```
.jss-1 {
  color: blue;
}
.jss-1:hover {
  color: green;
}
```

Further, JSS should allow nesting of such rules etc.

**Comment by kof** [comment]
Nope, you just didn't read documentation or its bad.

By default stylesheets are named, which means property name is just a name, not a selector. Selector is generated.

**Comment by kof** [comment]
You can do it right now with nested plugin https://github.com/jsstyles/jss-nested

**Comment by kof** [comment]
just updated readme.md and mentioned this more explicite, hope it helps ... we need a way better documentation anyways.
