### ISSUE TITLE
Jss Components

### ISSUE THREAD

**Issue by serapath** [jsstyles/jss#68]
I might have a component with a css file, a javascript file and an html template.
With the help of css2jss (in branch 15) i might be able to start using jss which then prefixes my classes and gives me access to the prefix during runtime.

How would I use that to not break my `templates` and javascript based `document.querySelector(...)` and the like? They have to be aware of the prefix, right?

**Comment by kof** [comment]
1. its now in jss-cli repository
2. jss isn't prefixing classes, jss-vendor-prefixer prefixes properties and values

**Comment by serapath** [comment]
Yes, i got confused, because https://github.com/jsstyles/jss#create-style-sheet-with-namespaces-enabled includes an example, where it prints:
```js
console.log(sheet.classes.myButton) // .jss-0
```

**Comment by kof** [comment]
why is it confusing, its a class generated by jss

**Comment by serapath** [comment]
I did not see:
```js
var sheet = jss.createStyleSheet({
    '.something': {
        width: '100px',
        height: '100px'
    }
}, {named: false}).attach()
```
which prevents the changes

**Comment by kof** [comment]
I don't undestand confusion, its an example for global selectors ....

**Comment by serapath** [comment]
My problem is, that `jss` without prefixing doesn't give me local scope for my css.
I can use [css-modulesify](https://github.com/css-modules/css-modulesify) to prefix and get my local scope instead...

Both approaches need me to adapt my `html templates` and `js DOM selectors`.
I could manually fix my templates and all the existing templates so that they will only work with the prefixed versions and do the same with the class based DOM selectors in javascript, but that would be error prone.

I understand, I could write the whole module in javascript, using for example `hyperscript` and `jss` and retrieve prefixes from `jss` to use them in my `hyperscript markup`. I have lots of projects that have `html`, `css` and `jss` which i would like to transition.

With `css2jss` and prefixing, i can start, I just wonder what to do with all my existing `templates` and `DOM selectors`

**Comment by kof** [comment]
You lost me somewhere in the middle, now give me code.

**Comment by serapath** [comment]
Given:
* `projectName/`
  * index.css
  * index.js
  * index.template.html


`$> npm init`
`$> npm install --save jss`
`$> npm install --save css-modulesify`
`$> browserify -t css-modulesify example/export-css.js | node > bundle.css`

(see: [example/export-css.js](https://github.com/css-modules/css-modulesify/blob/master/example/export-css.js))


```js
  // [index.js]
  var styles    = require('./bundle.css');
  var template  = require('./index.template.html');
  var css2jss   = require('jss/lib/cssToJss');
  var __        = document.createElement('div');
  
  
  module.exports = function projectName (parameter) {
  
    var arguments     = {};
    arguments.title   = parameter.title   || "Hello World";
    arguments.message = parameter.message || "Welcome to components";

    var component = (__.innerHTML=template;__.querySelector('.projectName'));
    var __title   = component.querySelector('.projectName__title');
    var __message = component.querySelector('.projectName__message');
  
    var sheet     = css2jss(styles.inner);
    
    __title.innerHTML   = argument.title;
    __message.innerHTML = argument.message;
    
    sheet.attach();
    document.body.appendChild(component);
  }

```

**Comment by serapath** [comment]
I'm not completely sure if I use `jss` the right way, but I have a lot of components that approximately look similar to the one above if you remove everything jss related.

In order to get `scoped css` I need to use the prefix feature of `css-modulesify` or the one provided by `jss-vendor-prefixer`, but that won't help me in my `javascript files` or in my `template files`.

Those don't know about the prefixes that were added and I wonder how to approach that.

**Comment by kof** [comment]
1. css2jss is actually created to be used serverside. So that we don't load pure css at all in the browser.
2. you mixed up vendor prefixer which is for props and values and dynamic jss classes generation.

**Comment by kof** [comment]
css2jss has been also created to translate pure css to jss without generated selectors ...

**Comment by kof** [comment]
now I am not sure whats the use case to use jss and css-modulesify together

**Comment by kof** [comment]
actually there is a good way to use them together.
We need to covert serverside css using css-modulesify into a json structure which uses names instead of selectors. Then we have a json which can be passed to jss and use classes generated by jss. This would be a nice enhancement for css2jss converter. It will make css2jss converter capable of producing namespaced jss code.

**Comment by kof** [comment]
So basically
1. convert css to jss serverside (convert `.something {...}` to  `{something: {...}}` )
2. `var sheet = jss.createStyleSheet({something: {...}})`
3. use regular jss: console.log(sheet.classes.something) // '.jss-0'

**Comment by kof** [comment]
Consider this still as a temporary approach to move fast to jss. Because this way you still can't reuse css code the way js allows it to do. Its still a very limited approach.

**Comment by serapath** [comment]
Ok, thx, at least my understanding improved a bit for now. I'll continue to follow this awesome project :-) thx
