### ISSUE TITLE
Can't run jss in a windowless environment

### ISSUE THREAD

**Issue by qimingweng** [jsstyles/jss#69]
When I have a file that is just `require('jss')`, and I run it in node like `node file.js`, it always returns this error: 

```
if (global[namespace] == null) global[namespace] = 0
          ^
TypeError: Cannot read property '__JSS_UID_PREFIX__' of undefined
```

The offending line is `jss/lib/uid.js:5:11`

This can be traced to the way the variable `global` is defined. This file will also not compile in node (I'm using 0.12.7, the newest one as of writing).

```
var global = typeof window === 'undefined' ? global : window;
global[0] = 0;
```

The error:
```
global[0] = 0;
          ^
TypeError: Cannot set property '0' of undefined
```

**Comment by qimingweng** [comment]
I created a pull request #70

**Comment by kof** [comment]
merged, thanks
