### ISSUE TITLE
Rewrite using ES6

### ISSUE THREAD

**Issue by kof** [jsstyles/jss#75]
use webpack, babel

**Comment by kof** [comment]
and add linter

**Comment by mpal9000** [comment]
Do you want some help on this?

**Comment by kof** [comment]
@mpal9000 almost finished the rewrite, restructuring the build. Could use some help to do the same for every plugin.

**Comment by mpal9000** [comment]
Do you use eslint? Can you push an .eslintrc file somewhere. so I can use it for the plugins?

**Comment by kof** [comment]
Yep, just wait a bit until I finish jss repository...

**Comment by mpal9000** [comment]
All right

**Comment by kof** [comment]
ok released 2.3.0  with es6 and webpack

**Comment by kof** [comment]
Examples are moved to jss-examples repository.
I think to move all examples from all plugins repositories to jss-examples. 

@mpal9000 take a look at the current state here

**Comment by kof** [comment]
@mpal9000 ping

**Comment by mpal9000** [comment]
@kof hey, I hadn't much free time the past few days, but I can start porting the plugins tomorrow.

**Comment by mpal9000** [comment]
@kof I have finished with the rewrite/repackaging of the official plugins + jss-examples. I will make the PRs tomorrow.
Some questions:
1) jss-debug doesn't work. There is no `rule.options.name` property. How do you want to proceed? I personaly don't use it.
2) In jss-examples, I am handling dist files for plugins like you do with jss.js (ie. copy from node_modules to the root dir). Do you want to put all copied files to .gitignore?
3) Do you want to convert all urls (examples, demos, external libs etc.) to https, if it's possible?
4) I used the .eslintrc file of the jss repo. Are you sure about the the `eqeqeq` rule? A few `==` can be left untouched. Maybe it's better to disable that rule.

For consistency I have changed the indentation to 2 spaces in most files that I edited/moved (html too). I think it's better to have the same indentation everywhere and 2 spaces is what you define in .eslintrc. It is better to have some more diffs now, because it is a rewrite/repackaging and there will be many changes anyway.

**Comment by kof** [comment]
1) true, I broke it by the recent changes in jss
2) 2 things: 
  - we need jss-examples to be self contained, otherwise they might break when jss changes
  - we need examples published on gh-pages so we need everything functional online, not only locally

**Comment by kof** [comment]
lets start with first PR before you do them all at once

**Comment by mpal9000** [comment]
I will push all changes to my forks in the next hour, to see them all together.

**Comment by mpal9000** [comment]
@kof check jss-camel-case/debug/extend/nested/props-sort/px/vendor-prefixer/examples
jss-debug doesn't work
jss-vendor-prefixer has a failing test

**Comment by kof** [comment]
@mpal9000 lets move all examples into jss-examples?

**Comment by kof** [comment]
How do you mean they don't work http://jsstyles.github.io/jss-camel-case/examples/simple/index.html

**Comment by kof** [comment]
Also we need to stop using jss from the main repository, it will break an example as soon as jss becomes incompatible, examples need to use specific versions, like its done in the main jss-examples repo.

**Comment by kof** [comment]
fixed jss-debug, now it just needs the latest jss version

**Comment by mpal9000** [comment]
> How do you mean they don't work http://jsstyles.github.io/jss-camel-case/examples/simple/index.html

What do you refer to?


> Also we need to stop using jss from the main repository, it will break an example as soon as jss becomes incompatible, examples need to use specific versions, like its done in the main jss-examples repo.

Specific versions for jss and the plugins are aready being used in my jss-examples fork. At least for examples in the new "plugins" directory. What do you mean?

**Comment by kof** [comment]
- the example here works http://jsstyles.github.io/jss-camel-case/examples/simple/index.html we just need to move/migrate it to jss-examples and fix links to it
- right now those plugin examples are using this http://jsstyles.github.io/jss/dist/jss.js , in jss-examples they use local jss, it will not be a problem when we did migration

**Comment by mpal9000** [comment]
* All the original examples are working. I didn't say anywhere they don't :-) About the move/migration I have already did it. ???
* Again, I have already fixed that in my fork of jss-examples

**Comment by kof** [comment]
oh I  misread something, great, lets start with the prs

**Comment by mpal9000** [comment]
OK, just wait a bit to add the new jss version where is needed, so jss-debug will work correctly.
Also there is a failing test in jss-vendor-prefixer (original & my fork).

**Comment by kof** [comment]
jss-vendor-prefixer test needs to be fixed, lets make it separate issue. Its the test itself which is broken. Not sure yet how to approach it.

**Comment by mpal9000** [comment]
OK, you I'll make the PR for that too and then it can be fixed on the rewritten code, because it's already broken.

**Comment by kof** [comment]
created an issue https://github.com/jsstyles/jss-vendor-prefixer/issues/5

**Comment by mpal9000** [comment]
http://jsstyles.github.io/jss/dist/jss.js is being used in "jss-*/test/index.html". "jss-*/test/local.html" is ok

**Comment by kof** [comment]
we need to use local jss everywhere, because this is going to break tests of plugins when they become incompatible with a certain version of jss

**Comment by kof** [comment]
In this case there is no point any mor to have local.html and index.html, it can be just index.html

**Comment by mpal9000** [comment]
OK, I think these two are being used only in readmes

**Comment by mpal9000** [comment]
I pushed all changes. Do you want to see them before make the PRs?

**Comment by kof** [comment]
PR's are designed to review changes and discuss them, feel free to create them)

**Comment by mpal9000** [comment]
:-)

**Comment by kof** [comment]
Ok all PR's are merged, that was a big amount of work, thank you.

**Comment by kof** [comment]
There are some other repos not in sync with our new infrastructure.

**Comment by kof** [comment]
@mpal9000 whats your twitter handle?

**Comment by mpal9000** [comment]
We can sync them the following days. I don't use twitter.

**Comment by mpal9000** [comment]
Which are these repos? cli and some details in the main one?

**Comment by kof** [comment]
all of them https://github.com/jsstyles except of those you rewrote already)

**Comment by kof** [comment]
@mpal9000 you are not in the contributors list because your commits are created by a different user than the one you use on github ... 

"Unrecognized author. If this is you, make sure mpal@mail.org is associated with your account. Click to add email addresses in your account settings."

**Comment by mpal9000** [comment]
Thanks for noticing. I changed my email on github recently (and removed the old one), but forgot to change it on git. Is it ok now? I will change the git email to the primary one that I added in github.

**Comment by kof** [comment]
closing this one
