### ISSUE TITLE
MAJOR: weird character / encoding issue in lib/uid.js

### ISSUE THREAD

**Issue by 0xR** [jsstyles/jss#76]
Error
=====
There is an invalid `0xc2` character in `lib/uid.js` as you can see in the hexdump I just retrieved from master:
```
000001f0  72 74 73 2e 72 65 73 65  74 20 3d 20 66 75 6e 63  |rts.reset = func|
00000200  74 69 6f 6e 28 29 c2 a0  7b 0a 20 20 20 20 63 6f  |tion()..{.    co|
00000210  75 6e 74 65 72 20 3d 20  30 0a 7d                 |unter = 0.}|
```

After running it through webpack I get this:
``` javacript
	exports.reset = function()Â {
	    counter = 0
	}
```

Background
==========
I'm trying out jss with webpack and the resulting javascript is invalid. At first I was blaming my webpack config so I removed everything to find the cause. Eventually I ended up with a close to empty webpack config. Before blaming webpack I looked at the orignal `uid.js` and found the error.

I also scanned the rest of the js files and it is only in this file and the non minified dist file.

Workaround
===========
Minifying with UglifyJS removes the invalid character.

**Comment by 0xR** [comment]
I am working an a PR

**Comment by kof** [comment]
yeah its  a bad whitespace again, will add a linter soon.
