### ISSUE TITLE
How to handle assets?

### ISSUE THREAD

**Issue by serapath** [jsstyles/jss#79]
In a local project, I can just reference the path to my assets, but if the local project becomes a module (component) and is installed into another project, those asset paths don't work anymore, because they point to assets nested into the `node_modules` folder now.

How could that problem be approached? Is it already solved?

**Comment by kof** [comment]
I think its an issue outside of jss scope, however I think people might have also stumbled over it so it might be worth mentioning some solutions in the documentation.

**Comment by kof** [comment]
In you particular case I assume you have assets installed as a dependency. If project is installed by itself assets are in node_modules/assets if its installed as a dependency and parent project has same assets as a dependency, assets relatively to your package are in ../node_modules/assets ... if this is the case a node path resolver needs to be used in a precompile step ...  or a path should be passed down to the component from the parent.

**Comment by serapath** [comment]
I was more thinking about a scenario, where i put the path to an asset in my `"json css"` (e.g. a "background-image url"  attached to a certain "css class")

Maybe it's a small "button component" with a repository structure like:
* `package.json`
* `index.js`
* `texture.jpg`
* `iconfont.woff`

The `index.js` might contain everything.
* The behavior logic through javascript
* The "html markup" through hyperscript or jsx
* The "css styling" through jss
* The assets (a custom font and a custom texture) references in the "jss"
  * `url(texture.jpg)`
  * `url(iconfont.woff)` (not even sure how to create a font face rule in jss)

A build step might produce `bundle.js` into the same folder, so the "asset paths" still make sense.

**BUT:**
If I `require('button-component')` the component, wherever my new `bundle.js` goes, the asset paths would still be:
* `url(texture.jpg)`
* `url(iconfont.woff)`

**but** the assets, because `button-component` was `npm install`ed, are now located in `node_modules/button-component/...` and need to be referenced as:
* `url(node_modules/button-component/texture.jpg)`
* `url(node_modules/button-component/iconfont.woff)`

**but** the `node_modules` directory is not always meant to be served, so it would be nice if a `"browserify jss transform"` or some other mechanism could find all the referenced assets and copy them to a `"custom/build/folder"` and change their name to a "hash" and at the same time, "re-writes" the references to that path, for example:
* `url(custom/build/folder/s9s4gjee.jpg)`
* `url(custom/build/folder/4j8wgjw.woff)`

**Comment by kof** [comment]
As I said I think you need to set the path to the assets at runtime or at build step. The first one can be achived if rules are returned by some function and this function accepts a path, the second if you use some placeholder and replace it at build step, webpack has  a plugin for it.

**Comment by kof** [comment]
Also you could inline everything base64 encoded at build step.

**Comment by serapath** [comment]
that's what i'm looking into now. But maybe passing an argument at runtime might do it too.

**Comment by serapath** [comment]
I found some modules that might help with the task:
* https://www.npmjs.com/package/datauri
* https://www.npmjs.com/package/urify-emitter
* https://www.npmjs.com/package/urify
* https://www.npmjs.com/package/static-eval

I guess `urify-emitter` solves the problem. Including it in a components `package.json` as a `transform` might already work. The `datauri(...)` function is the above mentioed `jssAsset (...)` function to wrap url's that point at assets.

**Comment by kof** [comment]
Do you want to send a PR for documentation?
