### ISSUE TITLE
Clarify order of plugins?

### ISSUE THREAD

**Issue by jupl** [jsstyles/jss#80]
Reading the documentation, the order of plugins piece implies that I should write this:

```js
jss.use(nested)
jss.use(extend)
jss.use(vendorPrefixer)
jss.use(camelCase)
jss.use(propsSort)
jss.use(px)
```

However, this was having issues as for instance I was getting properties like `-webkit-flex: 1px` (derived from `flex: 1`) from what I assume `jss-px` and `jss-vendor-prefixer` being in reverse order. I'm assuming that the order is meant to be like this instead:

```js
jss.use(px)
jss.use(propsSort)
jss.use(camelCase)
jss.use(vendorPrefixer)
jss.use(extend)
jss.use(nested)
```

If that is the case or if it is another order a PR can be done for a code snippet/change order/etc. to avoid confusion.

**Comment by kof** [comment]
you are right, px should be done before vendorPrefixer

**Comment by kof** [comment]
will update the documentation

**Comment by kof** [comment]
71dc38790e065be38e026badf950c5706676af9f
