### ISSUE TITLE
Named rules not generating when using @media only

### ISSUE THREAD

**Issue by jupl** [jsstyles/jss#81]
When I create a stylesheet and do something like this:

```js
sheet.addRules({
  something: { ... },
  '@media (max-width: 540px)':
    desktopOnly: {
      display: 'none'
    }
  }
})
```

I get `undefined` for `sheet.classes.desktopOnly`. In order to work I need to do this instead:

```js
sheet.addRules({
  something: { ... },
  desktopOnly: {},
  '@media (max-width: 540px)':
    desktopOnly: {
      display: 'none'
    }
  }
})
```

I only bring it up because in CSS I don't need to create an empty selector to use media queries, so if the latter is what needs to be used it should be documented.

**Comment by kof** [comment]
Just to understand what you do, why do you have a media rule which doesn't overwrites any normal rule? Can you show me the logic and template and more concrete example?

**Comment by jupl** [comment]
The example above is one where I want to do a selector for certain item widths like hide something when the display width is too small.

**Comment by kof** [comment]
ok, will try to support this just for the sake of clarity. But actually its a bad design to use classes this way. Much nicer is

```javascript
{
   item: {...},
  '@media (max-width: 540px)':
    item: {
      display: 'none'
    }
  }
}
```

**Comment by jupl** [comment]
I didn't have time to post the code that I was playing around with but I wrote it separately because I am toggling it to show/hide items, so I need it in a separate rule so I can toggle it.

**Comment by kof** [comment]
As I said I will try to support this case, my last message was a try to point you in a better way of writing css by not adding classes as "actions", instead classes are "subjects", names of your elements if you want. As you probably any ways described how an item should look like, item within @media becomes an override, so that parent rule is not just an empty object.

But you can ignore my advise as I see that people will use it in different ways and this seems to be confusing.

**Comment by kof** [comment]
@jupl please try out the latest version and let me know

**Comment by AlastairTaft** [comment]
I still seem to be getting this behaviour in version `3.11.0` and `react-jss` version `2.0.6`

I have the following styles

```js
const styles = {
  '@media (min-width: 992px)': {
    container: {
      width: '30%',
      height: '100%',
      left: '70%',
      position: 'fixed',
      overflow: 'hidden',
      display: 'flex',
      alignItems: 'center',
    },
}

class SidePanel extends Component {
  render = () => {
    var { classes } = this.props.sheet
    // This is undefined
    var testClass = classes.container
    debugger

    return <div className={classes.container}>
      {/* ... */}
    </div>	
  }
}
export default useSheet(SidePanel, styles)
```

**Comment by kof** [comment]
seems like there is no test for this and we got a regression.

**Comment by kof** [comment]
will be fixed asap

**Comment by kof** [comment]
test added, fixed, published

**Comment by AlastairTaft** [comment]
Nice one 👍

**Comment by fabiomazzone** [comment]
I think, i hit the bug again or am i doing something wrong here ? 
https://codesandbox.io/s/loving-darkness-rjnoi?file=/src/App.js
