### ISSUE TITLE
css2jss for easier authoring

### ISSUE THREAD

**Issue by serapath** [jsstyles/jss#82]
Is there already a "converter" module that can be use to convert existing css to jss?

**usecases:**
* create `jss` from `es6 templates` written in css
* read a css file from disk (e.g. with `require('fs')`) and inline it as a css string to be converted into `jss` at runtime by the "converter". A browserify (e.g. [brfs](https://www.npmjs.com/package/brfs)) transform would do the css string inlining.
* a `browserify transform` (e.g. "css2jssify") that would inline a css file as valid jss code everywhere you calls `require('style.css')

**Comment by serapath** [comment]
I just found [jss-cli](https://github.com/jsstyles/jss-cli) which seems to include the logic to make it happen. I remember that I have read in the past that there are no plans to make `cssToJss` a seperate module, right?

I'll continue to play around with `jss` and maybe in a few weeks, I would create some pull requests - one for a `css2jss` converter and one for the other issue regarding assets and data-uri's, but I'm very busy right now, so it might take some time.

In general, thank you for this awesome project, I'm following it for quite some time now and I really start to like it a lot :-)

**Comment by kof** [comment]
jss-cli is  a package you can install and use as any package, it contains the lib and the cli.

**Comment by kof** [comment]
just added api usage example

**Comment by kof** [comment]
> In general, thank you for this awesome project, I'm following it for quite some time now and I really start to like it a lot :-)

you are welcome)

**Comment by DenisIzmaylov** [comment]
@serapath Hey! Have a look at this: https://github.com/axept/prejss

**Comment by iamstarkov** [comment]
@DenisIzmaylov no, OP has different use cases
