### ISSUE TITLE
importing vendor stylesheets?

### ISSUE THREAD

**Issue by geekyme** [jsstyles/jss#83]
How does JSS handle the use case of importing vendor styles? For instance, bootstrap styles or styles from other plugins. 

Would I have to rewrite them in jss?

**Comment by kof** [comment]
give me your specific example, there are different ways.

**Comment by geekyme** [comment]
Ok. I use bootstrap.styl (bootstrap in stylus) and a vendor CSS cropper.css.

Previously when I use stylus I could just import both styles and they will all get compiled into the main bundle.

**Comment by kof** [comment]
1. you can convert bootstrap css to jss using [jss-cli](https://github.com/jsstyles/jss-cli)
2. I would extend those classes to use namspaced jss
```javascript
import bootstap from 'bootstrap'
export default {
    myButton: {
      ...bootstrap['.btn'],
      color: 'red'
    }
}
```

**Comment by kof** [comment]
css> jss converter is not well tested though, you will stumble over issues, I am happy to fix them or will accept prs.

**Comment by kof** [comment]
@geekyme so did it work for you, can we close this?

**Comment by geekyme** [comment]
I see. I have not tried this yet. I think jss is still a little too new for me so I went back to css processors or plain stylesheets.
