### ISSUE TITLE
Virtual CSS?

### ISSUE THREAD

**Issue by serapath** [jsstyles/jss#88]
Hey, while styling some stuff using jss, i started to add class selector like
* `button--deactivated`
* `button--disabled`
and then refactored to
* `deactivated`
* `disabled`
because it's anyway styling just inside the `button component`

At some point i started to feel stupid making up all those "state classes" and maintaining some "ui state" like, for example which of a collection of `navigation buttons` is currently `active` and therefor opens it's `submenu`...

**Then it occurred to me:**
Doesn't `jss` have those little cool helper functions? ...which allow me to do:
* `var color = sheet.getRule('.header').prop('background-color')`
* `var color = sheet.getRule('.header').prop('background-color', 'green')`

So I was starting to think whether I , instead of maintaining some `ui state` could just query my **ACTUAL UI STATE** which is right in front of me in the form of "jss sheet objects" and update certain things?
But then I was wondering whether that approach actually queries the DOM or CSSOM? or it just gives the value known by the "virtual jss sheet object"? ...because I don't want to make my website slow.

**Comment by kof** [comment]
1. I have the feeling that you don't need .prop, give me a full working code example of for e.g. one button, paste it on some playground
2. .prop is quering dom but once it did query value is cached and all next get calls are [fast](https://github.com/jsstyles/jss/blob/master/src/Rule.js#L81). Set calls will always use dom.

**Comment by serapath** [comment]
i'll work on an example - currently it's included in a more complex client code - but i'll isolate it and I'll also try to work on including `datauri` and `uri-emitter` to deal with assets.

Otherwise, when i use `.prop` to set a property and then `.prop` to get it, it will read from the cache?

**Comment by kof** [comment]
https://github.com/jsstyles/jss/blob/master/src/Rule.js#L68
